import { type Writable, writable } from "svelte/store";

type letter =
	| "A"
	| "B"
	| "C"
	| "D"
	| "E"
	| "F"
	| "G"
	| "H"
	| "I"
	| "J"
	| "K"
	| "L"
	| "M"
	| "N"
	| "O"
	| "P"
	| "Q"
	| "R"
	| "S"
	| "T"
	| "U"
	| "V"
	| "W"
	| "X"
	| "Y"
	| "Z";
export type iata =
	| `${letter}${letter}${letter}`;
export type airportClass =
	| "nonHub" /* Gray */
	| "altFocus" /* Dark Purple */
	| "focus" /* Purple */
	| "altRegional" /* Dark Green */
	| "secondary" /* Red */
	| "regional" /* Green */
	| "primary" /* Blue */;
export interface airportType {
	location: string;
	IATA: iata;
	latitude: number;
	longitude: number;
	state: `${letter}${letter}` | `${letter}${letter}${letter}`;
	enplanements: number;
	queryResult?: number; //When it is added
	connections: Partial<Record<iata, 
		connectionType
	>>;
	gates?: number; // Total number of gates at an airport
	interestMode?: boolean;
	population?: number;
	growthRate?: number;
	type?: airportClass;
	nearbyAirports?: string[];
	qrImpact?: number;
	popularityChange?: number;
	unassignedTravelers: number;
}
export interface connectionType {
	location: iata;
	travelers: number;
	interest: number
	gates: number;
	speed: number
}
export const airports: Writable<airportType[]> = writable([]);
export function getAirports(
	filter: (a: any) => boolean = () => true
): airportType[] {
	let airports: Partial<airportType>[] = [
		{
			location: "Allentown",
			IATA: "ABE",
			state: "PA",
			enplanements: 0.448,
			latitude: 40.652,
			longitude: -75.44,
		},
		{
			location: "Abilene",
			IATA: "ABI",
			state: "TX",
			enplanements: 0.095,
			latitude: 32.411,
			longitude: -99.682,
		},
		{
			location: "Albuquerque",
			IATA: "ABQ",
			state: "NM",
			enplanements: 2.69,
			latitude: 35.039,
			longitude: -106.608,
			nearbyAirports: [
				"SAF",
			],
		},
		{
			location: "Aberdeen",
			IATA: "ABR",
			state: "SD",
			enplanements: 0.024,
			latitude: 45.447,
			longitude: -98.422,
		},
		{
			location: "Albany",
			IATA: "ABY",
			state: "GA",
			enplanements: 0.03,
			latitude: 31.536,
			longitude: -84.194,
		},
		{
			location: "Nantucket",
			IATA: "ACK",
			state: "MA",
			enplanements: 0.154,
			latitude: 41.253,
			longitude: -70.061,
		},
		{
			location: "Waco",
			IATA: "ACT",
			state: "TX",
			enplanements: 0.054,
			latitude: 31.612,
			longitude: -97.23,
		},
		{
			location: "Arcata / Eureka",
			IATA: "ACV",
			state: "CA",
			enplanements: 0.134,
			latitude: 40.978,
			longitude: -124.108,
			nearbyAirports: [
				"CEC",
			],
		},
		{
			location: "Atlantic City",
			IATA: "ACY",
			state: "NJ",
			enplanements: 0.49,
			latitude: 39.458,
			longitude: -74.577,
		},
		{
			location: "Kodiak",
			IATA: "ADQ",
			state: "AK",
			enplanements: 0.087,
			latitude: 57.75,
			longitude: -152.494,
		},
		{
			location: "Alexandria",
			IATA: "AEX",
			state: "LA",
			enplanements: 0.205,
			latitude: 31.327,
			longitude: -92.549,
		},
		{
			location: "Augusta",
			IATA: "AGS",
			state: "GA",
			enplanements: 0.299,
			latitude: 33.37,
			longitude: -81.965,
		},
		{
			location: "Alliance",
			IATA: "AIA",
			state: "NE",
			enplanements: 0.004,
			latitude: 42.053,
			longitude: -102.804,
			nearbyAirports: [
				"BFF",
			],
			"qrImpact": -0.5,
		},
		{
			location: "King Salmon",
			IATA: "AKN",
			state: "AK",
			enplanements: 0.039,
			latitude: 58.676,
			longitude: -156.649,
		},
		{
			location: "Albany",
			IATA: "ALB",
			state: "NY",
			enplanements: 1.491,
			latitude: 42.749,
			longitude: -73.802,
		},
		{
			location: "Waterloo",
			IATA: "ALO",
			state: "IA",
			enplanements: 0.012,
			latitude: 42.558,
			longitude: -92.401,
		},
		{
			location: "Alamosa",
			IATA: "ALS",
			state: "CO",
			enplanements: 0.012,
			latitude: 37.435,
			longitude: -105.868,
		},
		{
			location: "Walla Walla",
			IATA: "ALW",
			state: "WA",
			enplanements: 0.037,
			latitude: 46.093,
			longitude: -118.284,
			nearbyAirports: [
				"PSC",
				"PDT",
			],
		},
		{
			location: "Amarillo",
			IATA: "AMA",
			state: "TX",
			enplanements: 0.402,
			latitude: 35.219,
			longitude: -101.706,
		},
		{
			location: "Anchorage",
			IATA: "ANC",
			state: "AK",
			enplanements: 2.268,
			latitude: 61.174,
			longitude: -149.998,
			nearbyAirports: [
				"MRI",
			],
		},
		{
			location: "Altoona",
			IATA: "AOO",
			state: "PA",
			enplanements: 0.005,
			latitude: 40.296,
			longitude: -78.32,
			nearbyAirports: [
				"JST",
			],
			"qrImpact": -0.5,
		},
		{
			location: "Alpena",
			IATA: "APN",
			state: "MI",
			enplanements: 0.011,
			latitude: 45.078,
			longitude: -83.56,
		},
		{
			location: "Watertown",
			IATA: "ART",
			state: "NY",
			enplanements: 0.023,
			latitude: 43.992,
			longitude: -76.019,
		},
		{
			location: "Aspen",
			IATA: "ASE",
			state: "CO",
			enplanements: 0.35,
			latitude: 39.222,
			longitude: -106.868,
			nearbyAirports: [
				"EGE",
			],
		},
		{
			location: "Atlanta",
			IATA: "ATL",
			state: "GA",
			enplanements: 23.866,
			latitude: 33.637,
			longitude: -84.428,
			nearbyAirports: [
				"PDK",
			],
		},
		{
			location: "Appleton",
			IATA: "ATW",
			state: "WI",
			enplanements: 0.54,
			latitude: 44.258,
			longitude: -88.519,
			nearbyAirports: [
				"GRB",
				"OSH",
			],
		},
		{
			location: "Watertown",
			IATA: "ATY",
			state: "SD",
			enplanements: 0.014,
			latitude: 44.914,
			longitude: -97.155,
		},
		{
			location: "Augusta",
			IATA: "AUG",
			state: "ME",
			enplanements: 0.005,
			latitude: 44.321,
			longitude: -69.797,
			nearbyAirports: [
				"PWM",
			],
		},
		{
			location: "Austin",
			IATA: "AUS",
			state: "TX",
			enplanements: 10.678,
			latitude: 30.195,
			longitude: -97.67,
		},
		{
			location: "Asheville",
			IATA: "AVL",
			state: "NC",
			enplanements: 1.096,
			latitude: 35.436,
			longitude: -82.542,
		},
		{
			location: "Scranton",
			IATA: "AVP",
			state: "PA",
			enplanements: 0.22,
			latitude: 41.338,
			longitude: -75.723,
		},
		{
			location: "Phoenix / Mesa",
			IATA: "AZA",
			state: "AZ",
			enplanements: 0.978,
			latitude: 33.30778,
			longitude: -111.65556,
			nearbyAirports: [
				"PHX",
				"SCF",
			],
		},
		{
			location: "Kalamazoo",
			IATA: "AZO",
			state: "MI",
			enplanements: 0.093,
			latitude: 42.234,
			longitude: -85.552,
		},
		{
			location: "Hartford",
			IATA: "BDL",
			state: "CT",
			enplanements: 3.285,
			latitude: 41.939,
			longitude: -72.684,
		},
		{
			location: "Bethel",
			IATA: "BET",
			state: "AK",
			enplanements: 0.166,
			latitude: 60.779,
			longitude: -161.837,
		},
		{
			location: "Bradford",
			IATA: "BFD",
			state: "PA",
			enplanements: 0.004,
			latitude: 41.803,
			longitude: -78.64,
		},
		{
			location: "Scottsbluff",
			IATA: "BFF",
			state: "NE",
			enplanements: 0.014,
			latitude: 41.874,
			longitude: -103.596,
			nearbyAirports: [
				"AIA",
			],
		},
		{
			location: "Seattle",
			IATA: "BFI",
			state: "WA",
			enplanements: 0.169,
			latitude: 47.53,
			longitude: -122.302,
			nearbyAirports: [
				"SEA",
				"PAE",
				"OLM",
			],
		},
		{
			location: "Bakersfield",
			IATA: "BFL",
			state: "CA",
			enplanements: 0.195,
			latitude: 35.434,
			longitude: -119.058,
		},
		{
			location: "Mobile (Downtown)",
			IATA: "BFM",
			enplanements: 0.02,
			state: "AL",
			longitude: -88.07,
			latitude: 30.63,
			nearbyAirports: [
				"MOB",
				"GUF",
			],
			"qrImpact": -1,
		},
		{
			location: "Binghamton",
			IATA: "BGM",
			state: "NY",
			enplanements: 0.024,
			latitude: 42.208,
			longitude: -75.98,
			nearbyAirports: [
				"ITH",
				"ELM",
			],
		},
		{
			location: "Bangor",
			IATA: "BGR",
			state: "ME",
			enplanements: 0.376,
			latitude: 44.807,
			longitude: -68.828,
			nearbyAirports: [
				"BHB",
			],
		},
		{
			location: "Bar Harbor",
			IATA: "BHB",
			state: "ME",
			enplanements: 0.011,
			latitude: 44.45,
			longitude: -68.361,
			nearbyAirports: [
				"BGR",
			],
		},
		{
			location: "Birmingham",
			IATA: "BHM",
			state: "AL",
			enplanements: 1.597,
			latitude: 33.564,
			longitude: -86.752,
		},
		{
			location: "Block Island",
			IATA: "BID",
			state: "RI",
			enplanements: 0.012,
			latitude: 41.168,
			longitude: -71.578,
		},
		{
			location: "Bishop",
			IATA: "BIH",
			state: "CA",
			enplanements: 0.01,
			latitude: 37.373,
			longitude: -118.364,
			nearbyAirports: [
				"MMH",
			],
		},
		{
			location: "Billings",
			IATA: "BIL",
			state: "MT",
			enplanements: 0.575,
			latitude: 45.808,
			longitude: -108.544,
		},
		{
			location: "Bismarck",
			IATA: "BIS",
			state: "ND",
			enplanements: 0.296,
			latitude: 46.773,
			longitude: -100.746,
		},
		{
			location: "Denver / Broomfield",
			IATA: "BJC",
			state: "CO",
			enplanements: 0.037,
			latitude: 39.908889,
			longitude: -105.117222,
			nearbyAirports: [
				"DEN",
				"FNL",
			],
		},
		{
			location: "Bemidji",
			IATA: "BJI",
			state: "MN",
			enplanements: 0.029,
			latitude: 47.511,
			longitude: -94.935,
		},
		{
			location: "Branson",
			IATA: "BKG",
			state: "MO",
			enplanements: 0.016,
			latitude: 36.53194,
			longitude: -93.20056,
			nearbyAirports: [
				"SGF",
				"HRO",
			],
		},
		{
			location: "Beckley",
			IATA: "BKW",
			state: "WV",
			enplanements: 0.006,
			latitude: 37.787,
			longitude: -81.124,
			nearbyAirports: [
				"LWB",
			],
		},
		{
			location: "Boulder City",
			IATA: "BLD",
			state: "NV",
			enplanements: 0.06,
			latitude: 35.94722,
			longitude: -114.86028,
			nearbyAirports: [
				"LAS",
			],
		},
		{
			location: "Bellingham",
			IATA: "BLI",
			state: "WA",
			enplanements: 0.307,
			latitude: 48.793,
			longitude: -122.538,
		},
		{
			location: "Belleville",
			IATA: "BLV",
			state: "IL",
			enplanements: 0.153,
			latitude: 38.545,
			longitude: -89.835,
			nearbyAirports: [
				"STL",
				"CPS",
				"STJ",
			],
		},
		{
			location: "Bloomington",
			IATA: "BMI",
			state: "IL",
			enplanements: 0.162,
			latitude: 40.477,
			longitude: -88.916,
			nearbyAirports: [
				"PIA",
			],
		},
		{
			location: "Nashville",
			IATA: "BNA",
			state: "TN",
			enplanements: 12.059,
			latitude: 36.124,
			longitude: -86.678,
		},
		{
			location: "Boise",
			IATA: "BOI",
			state: "ID",
			enplanements: 2.475,
			latitude: 43.564,
			longitude: -116.223,
		},
		{
			location: "Boston",
			IATA: "BOS",
			state: "MA",
			enplanements: 20.091,
			latitude: 42.363,
			longitude: -71.006,
			nearbyAirports: [
				"BED",
				"OWD",
				"MHT",
			],
		},
		{
			location: "Beaumont",
			IATA: "BPT",
			state: "TX",
			enplanements: 0.034,
			latitude: 29.951,
			longitude: -94.021,
			nearbyAirports: [
				"LCH",
			],
		},
		{
			location: "Brunswick",
			IATA: "BQK",
			state: "GA",
			enplanements: 0.043,
			latitude: 31.259,
			longitude: -81.466,
		},
		{
			location: "Aguadilla",
			IATA: "BQN",
			state: "PR",
			enplanements: 0.361,
			latitude: 18.495,
			longitude: -67.129,
		},
		{
			location: "Brainerd",
			IATA: "BRD",
			state: "MN",
			enplanements: 0.016,
			latitude: 46.404,
			longitude: -94.134,
		},
		{
			location: "Burlington",
			IATA: "BRL",
			state: "IA",
			enplanements: 0.004,
			latitude: 40.783,
			longitude: -91.126,
			"qrImpact": -0.5,
		},
		{
			location: "Brownsville",
			IATA: "BRO",
			state: "TX",
			enplanements: 0.188,
			latitude: 25.906,
			longitude: -97.426,
			nearbyAirports: [
				"HRL",
				"MFE",
			],
		},
		{
			location: "Utqiaġvik (Barrow)",
			IATA: "BRW",
			state: "AK",
			enplanements: 0.043,
			latitude: 71.285,
			longitude: -156.769,
		},
		{
			location: "Butte",
			IATA: "BTM",
			state: "MT",
			enplanements: 0.016,
			latitude: 45.955,
			longitude: -112.497,
			nearbyAirports: [
				"BZN",
				"WYS",
			],
		},
		{
			location: "Baton Rouge",
			IATA: "BTR",
			state: "LA",
			enplanements: 0.39,
			latitude: 30.533,
			longitude: -91.15,
			nearbyAirports: [
				"MSY",
			],
		},
		{
			location: "Burlington",
			IATA: "BTV",
			state: "VT",
			enplanements: 0.671,
			latitude: 44.472,
			longitude: -73.153,
			nearbyAirports: [
				"PBG",
			],
		},
		{
			location: "Buffalo",
			IATA: "BUF",
			state: "NY",
			enplanements: 2.499,
			latitude: 42.94,
			longitude: -78.731,
			nearbyAirports: [
				"IAG",
			],
		},
		{
			location: "Burbank",
			IATA: "BUR",
			state: "CA",
			enplanements: 3.383,
			latitude: 34.201,
			longitude: -118.359,
			nearbyAirports: [
				"HHR",
				"LAX",
				"LGB",
				"SNA",
				"ONT",
				"SBD",
				"RIV",
				"VNY",
			],
		},
		{
			location: "Baltimore",
			IATA: "BWI",
			state: "MD",
			enplanements: 13.221,
			latitude: 39.176,
			longitude: -76.669,
			nearbyAirports: [
				"DCA",
				"IAD",
			],
		},
		{
			location: "Bozeman",
			IATA: "BZN",
			state: "MT",
			enplanements: 0.722,
			latitude: 45.777,
			longitude: -111.15,
			nearbyAirports: [
				"BTM",
				"WYS",
			],
		},
		{
			location: "Columbia",
			IATA: "CAE",
			state: "SC",
			enplanements: 0.654,
			latitude: 33.939,
			longitude: -81.12,
		},
		{
			location: "Akron / Canton",
			IATA: "CAK",
			state: "OH",
			enplanements: 0.38,
			latitude: 40.915,
			longitude: -81.444,
		},
		{
			location: "Concord",
			IATA: "CCR",
			state: "CA",
			enplanements: 0.017,
			latitude: 37.989722,
			longitude: -122.056944,
			nearbyAirports: [
				"SFO",
				"SQL",
				"OAK",
				"SJC",
			],
		},
		{
			location: "Cedar City",
			IATA: "CDC",
			state: "UT",
			enplanements: 0.022,
			latitude: 37.701,
			longitude: -113.099,
			nearbyAirports: [
				"SGU",
			],
		},
		{
			location: "Cordova",
			IATA: "CDV",
			state: "AK",
			enplanements: 0.019,
			latitude: 60.492,
			longitude: -145.478,
		},
		{
			location: "Cresent City",
			IATA: "CEC",
			state: "CA",
			enplanements: 0.008,
			latitude: 41.78,
			longitude: -124.237,
			nearbyAirports: [
				"ACV",
			],
		},
		{
			location: "Cortez",
			IATA: "CEZ",
			state: "CO",
			enplanements: 0.009,
			latitude: 37.303,
			longitude: -108.628,
			nearbyAirports: [
				"DRO",
			],
		},
		{
			location: "Cape Girardeau",
			IATA: "CGI",
			state: "MO",
			enplanements: 0.009,
			latitude: 37.225,
			longitude: -89.571,
			nearbyAirports: [
				"MWA",
				"PAH",
			],
		},
		{
			location: "Chattanooga",
			IATA: "CHA",
			state: "TN",
			enplanements: 0.558,
			latitude: 35.035,
			longitude: -85.204,
		},
		{
			location: "Charlottesville",
			IATA: "CHO",
			state: "VA",
			enplanements: 0.351,
			latitude: 38.14,
			longitude: -78.452,
			nearbyAirports: [
				"SHD",
			],
		},
		{
			location: "Charleston",
			IATA: "CHS",
			state: "SC",
			enplanements: 3.115,
			latitude: 32.899,
			longitude: -80.041,
		},
		{
			location: "Cedar Rapids",
			IATA: "CID",
			state: "IA",
			enplanements: 0.76,
			latitude: 41.885,
			longitude: -91.711,
			nearbyAirports: [
				"IOW",
			],
		},
		{
			location: "Sault Ste. Marie",
			IATA: "CIU",
			state: "MI",
			enplanements: 0.026,
			latitude: 46.251,
			longitude: -84.472,
		},
		{
			location: "Clarksburg",
			IATA: "CKB",
			state: "WV",
			enplanements: 0.042,
			latitude: 39.298,
			longitude: -80.228,
			nearbyAirports: [
				"MGW",
			],
		},
		{
			location: "Carlsbad",
			IATA: "CLD",
			state: "CA",
			enplanements: 0.017,
			latitude: 33.128333,
			longitude: -117.28,
			nearbyAirports: [
				"SAN",
			],
		},
		{
			location: "Cleveland",
			IATA: "CLE",
			state: "OH",
			enplanements: 4.95,
			latitude: 41.409,
			longitude: -81.855,
		},
		{
			location: "College Station",
			IATA: "CLL",
			state: "TX",
			enplanements: 0.068,
			latitude: 30.588,
			longitude: -96.363,
		},
		{
			location: "Charlotte",
			IATA: "CLT",
			state: "NC",
			enplanements: 16.524,
			latitude: 35.213,
			longitude: -80.951,
			nearbyAirports: [
				"USA",
			],
		},
		{
			location: "Columbus",
			IATA: "CMH",
			state: "OH",
			enplanements: 3.887,
			latitude: 39.997,
			longitude: -82.892,
			nearbyAirports: [
				"LCK",
			],
		},
		{
			location: "Champaign",
			IATA: "CMI",
			state: "IL",
			enplanements: 0.087,
			latitude: 40.039,
			longitude: -88.277,
		},
		{
			location: "Houghton",
			IATA: "CMX",
			state: "MI",
			enplanements: 0.026,
			latitude: 47.168,
			longitude: -88.489,
		},
		{
			location: "Carlsbad",
			IATA: "CNM",
			state: "NM",
			enplanements: 0.004,
			latitude: 32.337,
			longitude: -104.263,
		},
		{
			location: "Moab",
			IATA: "CNY",
			state: "UT",
			enplanements: 0.011,
			latitude: 38.758,
			longitude: -109.753,
		},
		{
			location: "Cody",
			IATA: "COD",
			state: "WY",
			enplanements: 0.037,
			latitude: 44.52,
			longitude: -109.024,
		},
		{
			location: "Colorado Springs",
			IATA: "COS",
			state: "CO",
			enplanements: 1.248,
			latitude: 38.806,
			longitude: -104.701,
		},
		{
			location: "Columbia",
			IATA: "COU",
			state: "MO",
			enplanements: 0.103,
			latitude: 38.818,
			longitude: -92.218,
		},
		{
			location: "Casper",
			IATA: "CPR",
			state: "WY",
			enplanements: 0.1,
			latitude: 42.906,
			longitude: -106.464,
		},
		{
			location: "Culebra",
			IATA: "CPX",
			state: "PR",
			enplanements: 0.015,
			latitude: 18.313,
			longitude: -65.304,
		},
		{
			location: "Corpus Christi",
			IATA: "CRP",
			state: "TX",
			enplanements: 0.369,
			latitude: 27.772,
			longitude: -97.502,
		},
		{
			location: "Charleston",
			IATA: "CRW",
			state: "WV",
			enplanements: 0.202,
			latitude: 38.376,
			longitude: -81.593,
			nearbyAirports: [
				"HTS",
			],
		},
		{
			location: "Columbus",
			IATA: "CSG",
			state: "GA",
			enplanements: 0.063,
			latitude: 32.516,
			longitude: -84.939,
		},
		{
			location: "Cincinnati / Covington",
			IATA: "CVG",
			state: "OH",
			enplanements: 4,
			latitude: 39.049,
			longitude: -84.668,
			nearbyAirports: [
				"LUK",
			],
		},
		{
			location: "Clovis",
			IATA: "CVN",
			state: "NM",
			enplanements: 0.012,
			latitude: 34.427,
			longitude: -103.078,
		},
		{
			location: "Wausau",
			IATA: "CWA",
			state: "WI",
			enplanements: 0.09,
			latitude: 44.778,
			longitude: -89.666,
		},
		{
			location: "Coldfoot",
			IATA: "CXF",
			state: "AK",
			enplanements: 0.006,
			latitude: 67.252,
			longitude: -150.204,
		},
		{
			location: "Cheyenne",
			IATA: "CYS",
			state: "WY",
			enplanements: 0.028,
			latitude: 41.156,
			longitude: -104.81,
			nearbyAirports: [
				"LAR",
			],
		},
		{
			location: "Daytona Beach",
			IATA: "DAB",
			state: "FL",
			enplanements: 0.338,
			latitude: 29.18,
			longitude: -81.058,
		},
		{
			location: "Dallas",
			IATA: "DAL",
			state: "TX",
			enplanements: 8.655,
			latitude: 32.846,
			longitude: -96.851,
			nearbyAirports: [
				"DFW",
			],
		},
		{
			location: "Dayton",
			IATA: "DAY",
			state: "OH",
			enplanements: 0.825,
			latitude: 39.902,
			longitude: -84.219,
		},
		{
			location: "Dubuque",
			IATA: "DBQ",
			state: "IA",
			enplanements: 0.016,
			latitude: 42.402,
			longitude: -90.709,
		},
		{
			location: "Washington",
			IATA: "DCA",
			state: "DC",
			enplanements: 23.251,
			latitude: 38.851,
			longitude: -77.038,
			nearbyAirports: [
				"IAD",
				"BWI",
			],
		},
		{
			location: "Dodge City",
			IATA: "DDC",
			state: "KS",
			enplanements: 0.008,
			latitude: 37.763,
			longitude: -99.965,
			nearbyAirports: [
				"GCK",
			],
			"qrImpact": -0.5,
		},
		{
			location: "Decatur",
			IATA: "DEC",
			state: "IL",
			enplanements: 0.013,
			latitude: 39.835,
			longitude: -88.866,
			nearbyAirports: [
				"SPI",
			],
		},
		{
			location: "Denver",
			IATA: "DEN",
			state: "CO",
			enplanements: 22.646,
			latitude: 39.862,
			longitude: -104.673,
			nearbyAirports: [
				"FNL",
				"BJC",
			],
		},
		{
			location: "Dallas / Fort Worth",
			IATA: "DFW",
			state: "TX",
			enplanements: 24.351,
			latitude: 32.897,
			longitude: -97.038,
			nearbyAirports: [
				"DAL",
			],
		},
		{
			location: "Dothan",
			IATA: "DHN",
			state: "AL",
			enplanements: 0.039,
			latitude: 31.321,
			longitude: -85.449,
		},
		{
			location: "Dickinson",
			IATA: "DIK",
			state: "ND",
			enplanements: 0.026,
			latitude: 46.8,
			longitude: -102.804,
		},
		{
			location: "Dillingham",
			IATA: "DLG",
			state: "AK",
			enplanements: 0.035,
			latitude: 59.045,
			longitude: -158.506,
		},
		{
			location: "Duluth",
			IATA: "DLH",
			state: "MN",
			enplanements: 0.136,
			latitude: 46.842,
			longitude: -92.193,
			nearbyAirports: [
				"HIB",
			],
		},
		{
			location: "Durango",
			IATA: "DRO",
			state: "CO",
			enplanements: 0.251,
			latitude: 37.152,
			longitude: -107.754,
			nearbyAirports: [
				"CEZ",
			],
		},
		{
			location: "Del Rio",
			IATA: "DRT",
			state: "TX",
			enplanements: 0.005,
			latitude: 29.37417,
			longitude: -100.92722,
		},
		{
			location: "Des Moines",
			IATA: "DSM",
			state: "IA",
			enplanements: 1.555,
			latitude: 41.534,
			longitude: -93.663,
		},
		{
			location: "Detroit",
			IATA: "DTW",
			state: "MI",
			enplanements: 16.111,
			latitude: 42.212,
			longitude: -83.353,
		},
		{
			location: "DuBois",
			IATA: "DUJ",
			state: "PA",
			enplanements: 0.006,
			latitude: 41.178,
			longitude: -78.899,
		},
		{
			location: "Unalaska",
			IATA: "DUT",
			state: "AK",
			enplanements: 0.023,
			latitude: 53.899,
			longitude: -166.545,
		},
		{
			location: "Devils Lake",
			IATA: "DVL",
			state: "ND",
			enplanements: 0.009,
			latitude: 48.117,
			longitude: -98.91,
			"qrImpact": -0.5,
		},
		{
			location: "Kearney",
			IATA: "EAR",
			state: "NE",
			enplanements: 0.014,
			latitude: 40.727,
			longitude: -99.007,
			nearbyAirports: [
				"GRI",
			],
		},
		{
			location: "Wenatchee",
			IATA: "EAT",
			state: "WA",
			enplanements: 0.054,
			latitude: 47.399,
			longitude: -120.207,
		},
		{
			location: "Eau Claire",
			IATA: "EAU",
			state: "WI",
			enplanements: 0.022,
			latitude: 44.866,
			longitude: -91.484,
		},
		{
			location: "Panama City",
			IATA: "ECP",
			state: "FL",
			enplanements: 0.918,
			latitude: 30.358,
			longitude: -85.796,
			nearbyAirports: [
				"PNS",
				"VPS",
			],
		},
		{
			location: "Eagle",
			IATA: "EGE",
			state: "CO",
			enplanements: 0.283,
			latitude: 39.643,
			longitude: -106.916,
			nearbyAirports: [
				"ASE",
			],
		},
		{
			location: "Elko",
			IATA: "EKO",
			state: "NV",
			enplanements: 0.013,
			latitude: 40.825,
			longitude: -115.791,
		},
		{
			location: "El Dorado",
			IATA: "ELD",
			state: "AR",
			enplanements: 0.003,
			latitude: 33.221,
			longitude: -92.812,
			nearbyAirports: [
				"TXK",
			],
			"qrImpact": -0.5,
		},
		{
			location: "Elmira / Corning",
			IATA: "ELM",
			state: "NY",
			enplanements: 0.086,
			latitude: 42.16,
			longitude: -76.892,
			nearbyAirports: [
				"ITH",
				"BGM",
			],
		},
		{
			location: "El Paso",
			IATA: "ELP",
			state: "TX",
			enplanements: 2.072,
			latitude: 31.807,
			longitude: -106.376,
		},
		{
			location: "Emmonak",
			IATA: "EMK",
			state: "AK",
			enplanements: 0.01,
			latitude: 62.786111,
			longitude: -164.490833,
		},
		{
			location: "Kenai",
			IATA: "ENA",
			state: "AK",
			enplanements: 0.075,
			latitude: 60.573,
			longitude: -151.245,
		},
		{
			location: "Erie",
			IATA: "ERI",
			state: "PA",
			enplanements: 0.047,
			latitude: 42.083,
			longitude: -80.174,
		},
		{
			location: "Escanaba",
			IATA: "ESC",
			state: "MI",
			enplanements: 0.017,
			latitude: 45.723,
			longitude: -87.094,
			nearbyAirports: [
				"MQT",
				"IMT",
			],
		},
		{
			location: "Eastsound",
			IATA: "ESD",
			state: "WA",
			enplanements: 0.01,
			latitude: 48.70806,
			longitude: -122.91056,
			nearbyAirports: [
				"FRD",
			],
			"qrImpact": -0.5,
		},
		{
			location: "Eugene",
			IATA: "EUG",
			state: "OR",
			enplanements: 0.825,
			latitude: 44.125,
			longitude: -123.212,
		},
		{
			location: "Evansville",
			IATA: "EVV",
			state: "IN",
			enplanements: 0.19,
			latitude: 38.041,
			longitude: -87.528,
			nearbyAirports: [
				"OWB",
			],
		},
		{
			location: "New Bern",
			IATA: "EWN",
			state: "NC",
			enplanements: 0.097,
			latitude: 35.073,
			longitude: -77.043,
			nearbyAirports: [
				"ILM",
				"OAJ",
			],
		},
		{
			location: "Newark",
			IATA: "EWR",
			state: "NJ",
			enplanements: 10.514,
			latitude: 40.692,
			longitude: -74.169,
			nearbyAirports: [
				"JFK",
				"TEB",
				"LGA",
				"ISP",
				"HPN",
			],
		},
		{
			location: "Key West",
			IATA: "EYW",
			state: "FL",
			enplanements: 0.741,
			latitude: 24.556,
			longitude: -81.76,
		},
		{
			location: "Fairbanks",
			IATA: "FAI",
			state: "AK",
			enplanements: 0.574,
			latitude: 64.815,
			longitude: -147.857,
		},
		{
			location: "Fargo",
			IATA: "FAR",
			state: "ND",
			enplanements: 0.553,
			latitude: 46.921,
			longitude: -96.816,
		},
		{
			location: "Fresno",
			IATA: "FAT",
			state: "CA",
			enplanements: 1.318,
			latitude: 36.777,
			longitude: -119.719,
			nearbyAirports: [
				"VIS",
			],
		},
		{
			location: "Fayetteville",
			IATA: "FAY",
			state: "NC",
			enplanements: 0.168,
			latitude: 34.991,
			longitude: -78.88,
		},
		{
			location: "Kalispell",
			IATA: "FCA",
			state: "MT",
			enplanements: 0.404,
			latitude: 48.31056,
			longitude: -114.25611,
		},
		{
			location: "Flagstaff",
			IATA: "FLG",
			state: "AZ",
			enplanements: 0.079,
			latitude: 35.14,
			longitude: -111.669,
			nearbyAirports: [
				"SDX",
			],
		},
		{
			location: "Fort Lauderdale",
			IATA: "FLL",
			state: "FL",
			enplanements: 12.096,
			latitude: 26.072,
			longitude: -80.15,
			nearbyAirports: [
				"MIA",
				"PBI",
				"FXE",
			],
		},
		{
			location: "Florence",
			IATA: "FLO",
			state: "SC",
			enplanements: 0.025,
			latitude: 34.185,
			longitude: -79.724,
		},
		{
			location: "Fort Collins",
			IATA: "FNL",
			state: "CO",
			enplanements: 0.023,
			latitude: 40.451944,
			longitude: -105.011389,
			nearbyAirports: [
				"DEN",
				"BJC",
			],
		},
		{
			location: "Flint",
			IATA: "FNT",
			state: "MI",
			enplanements: 0.285,
			latitude: 42.965,
			longitude: -83.745,
			nearbyAirports: [
				"LAN",
			],
		},
		{
			location: "Fort Dodge",
			IATA: "FOD",
			state: "IA",
			enplanements: 0.008,
			latitude: 42.551,
			longitude: -94.192,
		},
		{
			location: "Topeka",
			IATA: "FOE",
			state: "KS",
			enplanements: 0.011,
			latitude: 38.950833,
			longitude: -95.663611,
		},
		{
			location: "Friday Harbor",
			IATA: "FRD",
			state: "WA",
			enplanements: 0.011,
			latitude: 48.52194,
			longitude: -123.02444,
			nearbyAirports: [
				"ESD",
			],
		},
		{
			location: "Sioux Falls",
			IATA: "FSD",
			state: "SD",
			enplanements: 0.701,
			latitude: 43.582,
			longitude: -96.742,
		},
		{
			location: "Fort Smith",
			IATA: "FSM",
			state: "AR",
			enplanements: 0.059,
			latitude: 35.337,
			longitude: -94.366,
			nearbyAirports: [
				"XNA",
			],
		},
		{
			location: "Fort Wayne",
			IATA: "FWA",
			state: "IN",
			enplanements: 0.424,
			latitude: 40.978,
			longitude: -85.195,
		},
		{
			location: "Fort Yukon",
			IATA: "FYU",
			state: "AK",
			enplanements: 0.005,
			latitude: 66.572,
			longitude: -145.246,
		},
		{
			location: "Galena",
			IATA: "GAL",
			state: "AK",
			enplanements: 0.012,
			latitude: 64.736,
			longitude: -156.935,
		},
		{
			location: "Gillette",
			IATA: "GCC",
			state: "WY",
			enplanements: 0.03,
			latitude: 44.349,
			longitude: -105.539,
		},
		{
			location: "Garden City",
			IATA: "GCK",
			state: "KS",
			enplanements: 0.031,
			latitude: 37.928,
			longitude: -100.724,
			nearbyAirports: [
				"DDC",
				"LBL",
			],
		},
		{
			location: "Grand Canyon",
			IATA: "GCN",
			state: "AZ",
			enplanements: 0.083,
			latitude: 35.952222,
			longitude: -112.146944,
		},
		{
			location: "Grand Canyon West",
			IATA: "GCW",
			state: "AZ",
			enplanements: 0.012,
			latitude: 35.990278,
			longitude: -113.816389,
		},
		{
			location: "Spokane",
			IATA: "GEG",
			state: "WA",
			enplanements: 2.064,
			latitude: 47.619,
			longitude: -117.535,
		},
		{
			location: "Grand Forks",
			IATA: "GFK",
			state: "ND",
			enplanements: 0.092,
			latitude: 47.948,
			longitude: -97.176,
			nearbyAirports: [
				"TVF",
			],
		},
		{
			location: "Longview",
			IATA: "GGG",
			state: "TX",
			enplanements: 0.035,
			latitude: 32.384,
			longitude: -94.712,
			nearbyAirports: [
				"TYR",
			],
		},
		{
			location: "Glasgow",
			IATA: "GGW",
			state: "MT",
			enplanements: 0.003,
			latitude: 48.212,
			longitude: -106.615,
			nearbyAirports: [
				"OLF",
			],
			"qrImpact": -0.5,
		},
		{
			location: "Grand Junction",
			IATA: "GJT",
			state: "CO",
			enplanements: 0.271,
			latitude: 39.122,
			longitude: -108.525,
		},
		{
			location: "Greenville",
			IATA: "GLH",
			state: "MS",
			enplanements: 0.007,
			latitude: 33.485,
			longitude: -90.984,
		},
		{
			location: "Gainesville",
			IATA: "GNV",
			state: "FL",
			enplanements: 0.291,
			latitude: 29.69,
			longitude: -82.272,
		},
		{
			location: "Gulfport",
			IATA: "GPT",
			state: "MS",
			enplanements: 0.425,
			latitude: 30.407,
			longitude: -89.07,
		},
		{
			location: "Green Bay",
			IATA: "GRB",
			state: "WI",
			enplanements: 0.538,
			latitude: 44.485,
			longitude: -88.13,
			nearbyAirports: [
				"ATW",
			],
		},
		{
			location: "Grand Island",
			IATA: "GRI",
			state: "NE",
			enplanements: 0.068,
			latitude: 40.968,
			longitude: -98.31,
			nearbyAirports: [
				"EAR",
			],
		},
		{
			location: "Killeen",
			IATA: "GRK",
			state: "TX",
			enplanements: 0.048,
			latitude: 31.067,
			longitude: -97.829,
		},
		{
			location: "Grand Rapids",
			IATA: "GRR",
			state: "MI",
			enplanements: 2.065,
			latitude: 42.881,
			longitude: -85.523,
			nearbyAirports: [
				"MKG",
			],
		},
		{
			location: "Greensboro",
			IATA: "GSO",
			state: "NC",
			enplanements: 0.986,
			latitude: 36.101,
			longitude: -79.941,
			nearbyAirports: [
				"INT",
			],
		},
		{
			location: "Greenville",
			IATA: "GSP",
			state: "SC",
			enplanements: 1.413,
			latitude: 34.896,
			longitude: -82.219,
		},
		{
			location: "Gustavus",
			IATA: "GST",
			state: "AK",
			enplanements: 0.01,
			latitude: 58.425,
			longitude: -135.707,
		},
		{
			location: "Great Falls",
			IATA: "GTF",
			state: "MT",
			enplanements: 0.187,
			latitude: 47.482,
			longitude: -111.37,
		},
		{
			location: "Columbus",
			IATA: "GTR",
			state: "MS",
			enplanements: 0.047,
			latitude: 33.448,
			longitude: -88.591,
		},
		{
			location: "Gunnison",
			IATA: "GUC",
			state: "CO",
			enplanements: 0.059,
			latitude: 38.534,
			longitude: -106.932,
		},
		{
			location: "Gulf Shores",
			IATA: "GUF",
			state: "AL",
			enplanements: 0.012,
			latitude: 30.2897,
			longitude: -87.6717,
			nearbyAirports: [
				"BFM",
				"MOB",
				"PNS",
			],
		},
		{
			location: "Agana",
			IATA: "GUM",
			state: "GU",
			enplanements: 0.933,
			latitude: 13.484,
			longitude: -215.203,
		},
		{
			location: "Gallup",
			IATA: "GUP",
			enplanements: 0.002,
			state: "NM",
			longitude: -108.79,
			latitude: 35.51,
			"qrImpact": -1,
		},
		{
			location: "Gary",
			IATA: "GYY",
			enplanements: 0.014,
			state: "IN",
			longitude: -87.41,
			latitude: 41.62,
			nearbyAirports: [
				"MDW",
				"ORD",
			],
			"qrImpact": -1,
		},
		{
			location: "Hayden",
			IATA: "HDN",
			state: "CO",
			enplanements: 0.227,
			latitude: 40.481,
			longitude: -107.218,
		},
		{
			location: "Hagerstown",
			IATA: "HGR",
			state: "MD",
			enplanements: 0.042,
			latitude: 39.709,
			longitude: -77.727,
		},
		{
			location: "Hilton Head",
			IATA: "HHH",
			state: "SC",
			enplanements: 0.109,
			latitude: 32.22444,
			longitude: -80.6975,
			nearbyAirports: [
				"SAV",
			],
		},
		{
			location: "Hibbing",
			IATA: "HIB",
			state: "MN",
			enplanements: 0.011,
			latitude: 47.387,
			longitude: -92.839,
			nearbyAirports: [
				"DLH",
			],
		},
		{
			location: "Helena",
			IATA: "HLN",
			state: "MT",
			enplanements: 0.102,
			latitude: 46.607,
			longitude: -111.983,
		},
		{
			location: "Hoonah",
			IATA: "HNH",
			state: "AK",
			enplanements: 0.006,
			latitude: 58.096,
			longitude: -135.409,
		},
		{
			location: "Honolulu, Oahu",
			IATA: "HNL",
			state: "HI",
			enplanements: 8.449,
			latitude: 21.318,
			longitude: -157.92,
		},
		{
			location: "Hana, Maui",
			IATA: "HNM",
			state: "HI",
			enplanements: 0.003,
			latitude: 20.796,
			longitude: -156.014,
		},
		{
			location: "Haines",
			IATA: "HNS",
			state: "AK",
			enplanements: 0.006,
			latitude: 59.244,
			longitude: -135.524,
			nearbyAirports: [
				"SGY",
			],
		},
		{
			location: "Hobbs",
			IATA: "HOB",
			state: "NM",
			enplanements: 0.026,
			latitude: 32.687,
			longitude: -103.218,
		},
		{
			location: "Homer",
			IATA: "HOM",
			state: "AK",
			enplanements: 0.027,
			latitude: 59.646,
			longitude: -151.477,
		},
		{
			location: "Hot Springs",
			IATA: "HOT",
			state: "AR",
			enplanements: 0.003,
			latitude: 34.478,
			longitude: -93.096,
			nearbyAirports: [
				"LIT",
			],
		},
		{
			location: "Houston (Hobby)",
			IATA: "HOU",
			state: "TX",
			enplanements: 5.117,
			latitude: 29.646,
			longitude: -95.277,
			nearbyAirports: [
				"IAH",
			],
		},
		{
			location: "White Plains",
			IATA: "HPN",
			state: "NY",
			enplanements: 1.182,
			latitude: 41.067,
			longitude: -73.708,
		},
		{
			location: "Harlingen",
			IATA: "HRL",
			state: "TX",
			enplanements: 0.504,
			latitude: 26.227,
			longitude: -97.655,
			nearbyAirports: [
				"BRO",
				"MFE",
			],
		},
		{
			location: "Harrison",
			IATA: "HRO",
			state: "AR",
			enplanements: 0.004,
			latitude: 36.262,
			longitude: -93.155,
			nearbyAirports: [
				"SGF",
				"BKG",
			],
			"qrImpact": -0.5,
		},
		{
			location: "Huntsville",
			IATA: "HSV",
			state: "AL",
			enplanements: 0.805,
			latitude: 34.637,
			longitude: -86.775,
			nearbyAirports: [
				"MSL",
			],
		},
		{
			location: "Huntington",
			IATA: "HTS",
			state: "WV",
			enplanements: 0.093,
			latitude: 38.369,
			longitude: -82.56,
			nearbyAirports: [
				"CRW",
			],
		},
		{
			location: "New Haven",
			IATA: "HVN",
			state: "CT",
			enplanements: 0.589,
			latitude: 41.264,
			longitude: -72.888,
		},
		{
			location: "Havre",
			IATA: "HVR",
			state: "MT",
			enplanements: 0.003,
			latitude: 48.543,
			longitude: -109.762,
			"qrImpact": -0.5,
		},
		{
			location: "Hyannis",
			IATA: "HYA",
			state: "MA",
			enplanements: 0.026,
			latitude: 41.669,
			longitude: -70.28,
		},
		{
			location: "Hays",
			IATA: "HYS",
			state: "KS",
			enplanements: 0.015,
			latitude: 38.842,
			longitude: -99.273,
		},
		{
			location: "Washington (Dulles)",
			IATA: "IAD",
			state: "DC",
			enplanements: 13.003,
			latitude: 38.947,
			longitude: -77.46,
			nearbyAirports: [
				"DCA",
				"IAD",
			],
		},
		{
			location: "Niagara Falls",
			IATA: "IAG",
			state: "NY",
			enplanements: 0.109,
			latitude: 43.108,
			longitude: -78.946,
			nearbyAirports: [
				"BUF",
			],
		},
		{
			location: "Houston",
			IATA: "IAH",
			state: "TX",
			enplanements: 23.349,
			latitude: 29.984,
			longitude: -95.341,
			nearbyAirports: [
				"HOU",
			],
		},
		{
			location: "Wichita",
			IATA: "ICT",
			state: "KS",
			enplanements: 0.886,
			latitude: 37.65,
			longitude: -97.433,
		},
		{
			location: "Idaho Falls",
			IATA: "IDA",
			state: "ID",
			enplanements: 0.302,
			latitude: 43.514,
			longitude: -112.071,
			nearbyAirports: [
				"PIH",
			],
		},
		{
			location: "Bullhead City / Laughlin",
			IATA: "IFP",
			state: "NV",
			enplanements: 0.073,
			latitude: 35.156111,
			longitude: -114.559444,
		},
		{
			location: "Wilmington",
			IATA: "ILG",
			state: "DE",
			enplanements: 0.125,
			latitude: 39.679,
			longitude: -75.607,
			nearbyAirports: [
				"PHL",
			],
		},
		{
			location: "Wilmington",
			IATA: "ILM",
			state: "NC",
			enplanements: 0.737,
			latitude: 34.271,
			longitude: -77.903,
			nearbyAirports: [
				"OAJ",
				"EWN",
			],
		},
		{
			location: "Imperial / El Centro",
			IATA: "IPL",
			state: "CA",
			enplanements: 0.009,
			latitude: 32.834167,
			longitude: -115.578611,
			nearbyAirports: [
				"YUM",
			],
		},
		{
			location: "Iron Mountain",
			IATA: "IMT",
			state: "MI",
			enplanements: 0.019,
			latitude: 45.818,
			longitude: -88.115,
			nearbyAirports: [
				"MQT",
				"ESC",
			],
		},
		{
			location: "Indianapolis",
			IATA: "IND",
			state: "IN",
			enplanements: 5.182,
			latitude: 39.717,
			longitude: -86.295,
			nearbyAirports: [
				"BMG",
			],
		},
		{
			location: "International Falls",
			IATA: "INL",
			state: "MN",
			enplanements: 0.015,
			latitude: 48.566,
			longitude: -93.402,
		},
		{
			location: "Williamsport",
			IATA: "IPT",
			state: "PA",
			enplanements: 0.023,
			latitude: 41.241667,
			longitude: -76.921667,
		},
		{
			location: "Kirksville",
			IATA: "IRK",
			state: "MO",
			enplanements: 0.006,
			latitude: 40.093,
			longitude: -92.545,
			nearbyAirports: [
				"UIN",
			],
		},
		{
			location: "Long Island (Islip)",
			IATA: "ISP",
			state: "NY",
			enplanements: 0.683,
			latitude: 40.796,
			longitude: -73.101,
			nearbyAirports: [
				"LGA",
				"JFK",
				"TEB",
				"EWR",
				"HPN",
			],
		},
		{
			location: "Ithaca",
			IATA: "ITH",
			state: "NY",
			enplanements: 0.07,
			latitude: 42.491,
			longitude: -76.459,
			nearbyAirports: [
				"BGM",
				"ELM",
			],
		},
		{
			location: "Hilo, Hawaii",
			IATA: "ITO",
			state: "HI",
			enplanements: 0.681,
			latitude: 19.72,
			longitude: -155.048,
		},
		{
			location: "Ironwood",
			IATA: "IWD",
			state: "MI",
			enplanements: 0.007,
			latitude: 46.527,
			longitude: -90.131,
		},
		{
			location: "Jackson",
			IATA: "JAC",
			state: "WY",
			enplanements: 0.519,
			latitude: 43.607,
			longitude: -110.738,
		},
		{
			location: "Jackson",
			IATA: "JAN",
			state: "MS",
			enplanements: 0.617,
			latitude: 32.311,
			longitude: -90.076,
		},
		{
			location: "Jacksonville",
			IATA: "JAX",
			state: "FL",
			enplanements: 3.75,
			latitude: 30.494,
			longitude: -81.688,
			nearbyAirports: [
				"UST",
			],
		},
		{
			location: "Jonesboro",
			IATA: "JBR",
			enplanements: 0.002,
			state: "AR",
			longitude: -90.65,
			latitude: 35.83,
			nearbyAirports: [
				"MEM",
			],
			"qrImpact": -1,
		},
		{
			location: "New York",
			IATA: "JFK",
			state: "NY",
			enplanements: 25.466,
			latitude: 40.64,
			longitude: -73.779,
			nearbyAirports: [
				"EWR",
				"TEB",
				"LGA",
				"ISP",
				"HPN",
			],
		},
		{
			location: "Lahaina, Maui",
			IATA: "JHM",
			state: "HI",
			enplanements: 0.008,
			latitude: 20.963056,
			longitude: -156.673056,
		},
		{
			location: "Joplin",
			IATA: "JLN",
			state: "MO",
			enplanements: 0.018,
			latitude: 37.153,
			longitude: -94.499,
		},
		{
			location: "Jamestown",
			IATA: "JMS",
			state: "ND",
			enplanements: 0.01,
			latitude: 46.93,
			longitude: -98.678,
		},
		{
			location: "Juneau",
			IATA: "JNU",
			state: "AK",
			enplanements: 0.436,
			latitude: 58.355,
			longitude: -134.578,
		},
		{
			location: "Johnstown",
			IATA: "JST",
			state: "PA",
			enplanements: 0.018,
			latitude: 40.316,
			longitude: -78.835,
			nearbyAirports: [
				"AOO",
				"LBE",
			],
			"qrImpact": -0.5,
		},
		{
			location: "Klawock",
			IATA: "KLW",
			state: "AK",
			enplanements: 0.016,
			latitude: 55.57917,
			longitude: -133.07611,
		},
		{
			location: "Kailua-Kona, Hawaii",
			IATA: "KOA",
			state: "HI",
			enplanements: 2.024,
			latitude: 19.733,
			longitude: -156.046,
		},
		{
			location: "Ketchikan",
			IATA: "KTN",
			state: "AK",
			enplanements: 0.152,
			latitude: 55.354,
			longitude: -131.711,
		},
		{
			location: "Lafayette",
			IATA: "LAF",
			state: "IN",
			enplanements: 0.006,
			latitude: 40.412,
			longitude: -86.937,
			"qrImpact": -0.5,
		},
		{
			location: "Lakeland",
			IATA: "LAL",
			state: "FL",
			enplanements: 0.054,
			latitude: 27.988,
			longitude: -82.019,
			nearbyAirports: [
				"TPA",
				"MCO",
			],
		},
		{
			location: "Lansing",
			IATA: "LAN",
			state: "MI",
			enplanements: 0.124,
			latitude: 42.779,
			longitude: -84.586,
			nearbyAirports: [
				"FNT",
			],
		},
		{
			location: "Laramie",
			IATA: "LAR",
			state: "WY",
			enplanements: 0.019,
			latitude: 41.312,
			longitude: -105.675,
			nearbyAirports: [
				"CYS",
			],
		},
		{
			location: "Las Vegas",
			IATA: "LAS",
			state: "NV",
			enplanements: 20.245,
			latitude: 36.08,
			longitude: -115.152,
			nearbyAirports: [
				"BLD",
			],
		},
		{
			location: "Lawton",
			IATA: "LAW",
			state: "OK",
			enplanements: 0.045,
			latitude: 34.568,
			longitude: -98.417,
			nearbyAirports: [
				"SPS",
			],
		},
		{
			location: "Los Angeles",
			IATA: "LAX",
			state: "CA",
			enplanements: 25.261,
			latitude: 33.943,
			longitude: -118.408,
			nearbyAirports: [
				"BUR",
				"HHR",
				"LGB",
				"SNA",
				"ONT",
				"SBD",
				"RIV",
				"VNY",
			],
		},
		{
			location: "Lubbock",
			IATA: "LBB",
			state: "TX",
			enplanements: 0.563,
			latitude: 33.664,
			longitude: -101.821,
		},
		{
			location: "Latrobe",
			IATA: "LBE",
			state: "PA",
			enplanements: 0.076,
			latitude: 40.273,
			longitude: -79.41,
			nearbyAirports: [
				"PIT",
				"JST",
			],
			"qrImpact": -0.5,
		},
		{
			location: "North Platte",
			IATA: "LBF",
			state: "NE",
			enplanements: 0.017,
			latitude: 41.126,
			longitude: -100.684,
			nearbyAirports: [
				"MCK",
			],
		},
		{
			location: "Liberal",
			IATA: "LBL",
			state: "KS",
			enplanements: 0.008,
			latitude: 37.044,
			longitude: -100.96,
			nearbyAirports: [
				"GCK",
			],
			"qrImpact": -0.5,
		},
		{
			location: "Lake Charles",
			IATA: "LCH",
			state: "LA",
			enplanements: 0.091,
			latitude: 30.126,
			longitude: -93.223,
			nearbyAirports: [
				"BPT",
			],
		},
		{
			location: "Columbus (Rickenbacker)",
			IATA: "LCK",
			state: "OH",
			enplanements: 0.143,
			latitude: 39.814,
			longitude: -82.928,
			nearbyAirports: [
				"CMH",
			],
		},
		{
			location: "Lebanon",
			IATA: "LEB",
			state: "NH",
			enplanements: 0.011,
			latitude: 43.626,
			longitude: -72.304,
		},
		{
			location: "Lexington",
			IATA: "LEX",
			state: "KY",
			enplanements: 0.776,
			latitude: 38.037,
			longitude: -84.609,
		},
		{
			location: "Lafayette",
			IATA: "LFT",
			state: "LA",
			enplanements: 0.264,
			latitude: 30.205,
			longitude: -91.988,
		},
		{
			location: "New York (LaGuardia)",
			IATA: "LGA",
			state: "NY",
			enplanements: 10.716,
			latitude: 40.777,
			longitude: -73.873,
			nearbyAirports: [
				"JFK",
				"TEB",
				"EWR",
				"ISP",
				"HPN",
			],
		},
		{
			location: "Long Beach",
			IATA: "LGB",
			state: "CA",
			enplanements: 2.032,
			latitude: 33.818,
			longitude: -118.152,
			nearbyAirports: [
				"BUR",
				"HHR",
				"LAX",
				"SNA",
				"ONT",
				"SBD",
				"RIV",
				"VNY",
			],
		},
		{
			location: "Lihue, Kauai",
			IATA: "LIH",
			state: "HI",
			enplanements: 1.777,
			latitude: 21.976,
			longitude: -159.339,
		},
		{
			location: "Little Rock",
			IATA: "LIT",
			state: "AR",
			enplanements: 1.146,
			latitude: 34.729,
			longitude: -92.225,
			nearbyAirports: [
				"HOT",
			],
		},
		{
			location: "Lincoln",
			IATA: "LNK",
			state: "NE",
			enplanements: 0.13,
			latitude: 40.851,
			longitude: -96.759,
			nearbyAirports: [
				"OMA",
			],
		},
		{
			location: "Lancaster",
			IATA: "LNS",
			state: "PA",
			enplanements: 0.008,
			latitude: 40.122,
			longitude: -76.294,
			nearbyAirports: [
				"MDT",
			],
		},
		{
			location: "Lanai City, Lanai",
			IATA: "LNY",
			state: "HI",
			enplanements: 0.025,
			latitude: 20.786,
			longitude: -156.951,
		},
		{
			location: "Laredo",
			IATA: "LRD",
			state: "TX",
			enplanements: 0.173,
			latitude: 27.544,
			longitude: -99.462,
		},
		{
			location: "La Crosse",
			IATA: "LSE",
			state: "WI",
			enplanements: 0.041,
			latitude: 43.879,
			longitude: -91.257,
		},
		{
			location: "Kalaupapa, Molokai",
			IATA: "LUP",
			state: "HI",
			enplanements: 0.004,
			latitude: 21.211,
			longitude: -156.974,
		},
		{
			location: "Lewisburg",
			IATA: "LWB",
			state: "WV",
			enplanements: 0.009,
			latitude: 37.858,
			longitude: -80.399,
			nearbyAirports: [
				"BKW",
			],
		},
		{
			location: "Lewiston",
			IATA: "LWS",
			state: "ID",
			enplanements: 0.055,
			latitude: 46.375,
			longitude: -117.015,
			nearbyAirports: [
				"PUW",
			],
			"qrImpact": -0.5,
		},
		{
			location: "Lynchburg",
			IATA: "LYH",
			state: "VA",
			enplanements: 0.081,
			latitude: 37.325,
			longitude: -79.201,
			nearbyAirports: [
				"ROA",
			],
		},
		{
			location: "Midland",
			IATA: "MAF",
			state: "TX",
			enplanements: 0.762,
			latitude: 31.943,
			longitude: -102.202,
		},
		{
			location: "Majuro",
			IATA: "MAJ",
			state: "MH",
			enplanements: 0.976,
			latitude: 7.064722,
			longitude: -188.728056,
		},
		{
			location: "Mayaquez",
			IATA: "MAZ",
			state: "PR",
			enplanements: 0.009,
			latitude: 18.256,
			longitude: -67.148,
		},
		{
			location: "Manistee",
			IATA: "MBL",
			state: "MI",
			enplanements: 0.007,
			latitude: 44.272,
			longitude: -86.247,
			nearbyAirports: [
				"TVC",
			],
		},
		{
			location: "Saginaw",
			IATA: "MBS",
			state: "MI",
			enplanements: 0.075,
			latitude: 43.533,
			longitude: -84.08,
		},
		{
			location: "Merced",
			IATA: "MCE",
			state: "CA",
			enplanements: 0.005,
			latitude: 37.285,
			longitude: -120.514,
			nearbyAirports: [
				"SCK",
				"MOD",
			],
			"qrImpact": -0.5,
		},
		{
			location: "Kansas City",
			IATA: "MCI",
			state: "MO",
			enplanements: 5.915,
			latitude: 39.298,
			longitude: -94.714,
			nearbyAirports: [
				"MKC",
			],
		},
		{
			location: "Macon",
			IATA: "MCN",
			state: "GA",
			enplanements: 0.017,
			latitude: 32.693,
			longitude: -83.649,
		},
		{
			location: "Orlando",
			IATA: "MCO",
			state: "FL",
			enplanements: 23.36,
			latitude: 28.429,
			longitude: -81.309,
			nearbyAirports: [
				"SFB",
				"LAL",
			],
		},
		{
			location: "Mason City",
			IATA: "MCW",
			state: "IA",
			enplanements: 0.007,
			latitude: 43.158,
			longitude: -93.331,
		},
		{
			location: "Harrisburg",
			IATA: "MDT",
			state: "PA",
			enplanements: 0.727,
			latitude: 40.193,
			longitude: -76.763,
			nearbyAirports: [
				"LNS",
			],
		},
		{
			location: "Chicago (Midway)",
			IATA: "MDW",
			state: "IL",
			enplanements: 10.36,
			latitude: 41.786,
			longitude: -87.753,
			nearbyAirports: [
				"ORD",
				"MKE",
				"GYY",
			],
		},
		{
			location: "Midway Atoll",
			IATA: "MDY",
			enplanements: 0.01942,
			state: "UM",
			longitude: -177.38,
			latitude: 28.2,
			"qrImpact": -1,
		},
		{
			location: "Meridian",
			IATA: "MEI",
			state: "MS",
			enplanements: 0.017,
			latitude: 32.333,
			longitude: -88.752,
		},
		{
			location: "Memphis",
			IATA: "MEM",
			state: "TN",
			enplanements: 2.439,
			latitude: 35.042,
			longitude: -89.977,
			nearbyAirports: [
				"JBR",
			],
		},
		{
			location: "McAllen",
			IATA: "MFE",
			state: "TX",
			enplanements: 0.626,
			latitude: 26.176,
			longitude: -98.239,
			nearbyAirports: [
				"BRO",
				"HRL",
			],
		},
		{
			location: "Medford",
			IATA: "MFR",
			state: "OR",
			enplanements: 0.504,
			latitude: 42.375,
			longitude: -122.873,
			nearbyAirports: [
				"LMT",
			],
		},
		{
			location: "Montgomery",
			IATA: "MGM",
			state: "AL",
			enplanements: 0.194,
			latitude: 32.301,
			longitude: -86.394,
		},
		{
			location: "Morgantown",
			IATA: "MGW",
			state: "WV",
			enplanements: 0.008,
			latitude: 39.644,
			longitude: -79.918,
			nearbyAirports: [
				"CKB",
			],
		},
		{
			location: "Manhattan",
			IATA: "MHK",
			state: "KS",
			enplanements: 0.086,
			latitude: 39.141,
			longitude: -96.672,
		},
		{
			location: "Manchester",
			IATA: "MHT",
			state: "NH",
			enplanements: 1.133,
			latitude: 42.933,
			longitude: -71.436,
			nearbyAirports: [
				"BOS",
			],
		},
		{
			location: "Miami",
			IATA: "MIA",
			state: "FL",
			enplanements: 23.588,
			latitude: 25.795,
			longitude: -80.29,
			nearbyAirports: [
				"PBI",
				"FLL",
				"FXE",
			],
		},
		{
			location: "Kansas City (Downtown)",
			IATA: "MKC",
			state: "MO",
			enplanements: 0.014,
			latitude: 39.123056,
			longitude: -94.592778,
			nearbyAirports: [
				"MCI",
				"STJ",
			],
		},
		{
			location: "Milwaukee",
			IATA: "MKE",
			state: "WI",
			enplanements: 3.104,
			latitude: 42.947,
			longitude: -87.897,
			nearbyAirports: [
				"ORD",
				"MDW",
			],
		},
		{
			location: "Muskegon",
			IATA: "MKG",
			state: "MI",
			enplanements: 0.003,
			latitude: 43.168,
			longitude: -86.235,
			nearbyAirports: [
				"GRR",
			],
			"qrImpact": -0.5,
		},
		{
			location: "Kaunakakai, Molokai",
			IATA: "MKK",
			state: "HI",
			enplanements: 0.104,
			latitude: 21.153,
			longitude: -157.096,
		},
		{
			location: "Jackson",
			IATA: "MKL",
			state: "TN",
			enplanements: 0.003,
			latitude: 35.6,
			longitude: -88.916,
		},
		{
			location: "Melbourne",
			IATA: "MLB",
			state: "FL",
			enplanements: 0.348,
			latitude: 28.103,
			longitude: -80.645,
			nearbyAirports: [
				"VRB",
				"MCO"
			],
		},
		{
			location: "Moline",
			IATA: "MLI",
			state: "IL",
			enplanements: 0.327,
			latitude: 41.448,
			longitude: -90.508,
		},
		{
			location: "Monroe",
			IATA: "MLU",
			state: "LA",
			enplanements: 0.105,
			latitude: 32.511,
			longitude: -92.036,
		},
		{
			location: "Mammoth Lakes",
			IATA: "MMH",
			state: "CA",
			enplanements: 0.004,
			latitude: 37.624,
			longitude: -118.839,
			nearbyAirports: [
				"BIH",
			],
		},
		{
			location: "Mobile",
			IATA: "MOB",
			state: "AL",
			enplanements: 0.314,
			latitude: 30.691,
			longitude: -88.243,
			nearbyAirports: [
				"BFM",
			],
		},
		{
			location: "Modesto",
			IATA: "MOD",
			latitude: 37.63,
			longitude: -120.95,
			state: "CA",
			enplanements: 0.018,
			"qrImpact": -1,
			nearbyAirports: [
				"SCK",
				"MCE",
			],
		},
		{
			location: "Minot",
			IATA: "MOT",
			state: "ND",
			enplanements: 0.169,
			latitude: 48.258,
			longitude: -101.278,
		},
		{
			location: "Marquette",
			IATA: "MQT",
			state: "MI",
			enplanements: 0.054,
			latitude: 46.35361,
			longitude: -87.39528,
			nearbyAirports: [
				"ESC",
				"IMT",
			],
		},
		{
			location: "Anchorage (Merril)",
			IATA: "MRI",
			enplanements: 0.032,
			state: "AK",
			longitude: -149.84,
			latitude: 61.21,
			nearbyAirports: [
				"ANC",
			],
			"qrImpact": -1,
		},
		{
			location: "Monterey",
			IATA: "MRY",
			state: "CA",
			enplanements: 0.305,
			latitude: 36.587,
			longitude: -121.843,
		},
		{
			location: "Muscle Shoals",
			IATA: "MSL",
			state: "AL",
			enplanements: 0.007,
			latitude: 34.745,
			longitude: -87.61,
			nearbyAirports: [
				"HSV",
			],
		},
		{
			location: "Madison",
			IATA: "MSN",
			state: "WI",
			enplanements: 1.156,
			latitude: 43.14,
			longitude: -89.338,
		},
		{
			location: "Missoula",
			IATA: "MSO",
			state: "MT",
			enplanements: 0.512,
			latitude: 46.916,
			longitude: -114.091,
		},
		{
			location: "Minneapolis / St. Paul",
			IATA: "MSP",
			state: "MN",
			enplanements: 20.554,
			latitude: 44.882,
			longitude: -93.222,
		},
		{
			location: "Massena",
			IATA: "MSS",
			state: "NY",
			enplanements: 0.005,
			latitude: 44.936,
			longitude: -74.845,
			nearbyAirports: [
				"OGS",
				"SLK",
			],
			"qrImpact": -0.5,
		},
		{
			location: "New Orleans",
			IATA: "MSY",
			state: "LA",
			enplanements: 6.537,
			latitude: 29.993,
			longitude: -90.259,
			nearbyAirports: [
				"BTR",
			],
		},
		{
			location: "Montrose",
			IATA: "MTJ",
			state: "CO",
			enplanements: 0.265,
			latitude: 38.51,
			longitude: -107.894,
		},
		{
			location: "Waimea, Hawaii",
			IATA: "MUE",
			state: "HI",
			enplanements: 0.004,
			latitude: 20.001,
			longitude: -155.668,
		},
		{
			location: "Martha's Vineyard",
			IATA: "MVY",
			state: "MA",
			enplanements: 0.083,
			latitude: 41.393,
			longitude: -70.614,
		},
		{
			location: "Marion",
			IATA: "MWA",
			state: "IL",
			enplanements: 0.014,
			latitude: 37.755,
			longitude: -89.011,
			nearbyAirports: [
				"CGI",
				"PAH",
			],
		},
		{
			location: "Myrtle Beach",
			IATA: "MYR",
			state: "SC",
			enplanements: 1.895,
			latitude: 33.68,
			longitude: -78.928,
		},
		{
			location: "Ceiba",
			IATA: "NRR",
			state: "PR",
			enplanements: 0.02,
			latitude: 18.24528,
			longitude: -65.64333,
		},
		{
			location: "Jacksonville",
			IATA: "OAJ",
			state: "NC",
			enplanements: 0.146,
			latitude: 34.829,
			longitude: -77.612,
			nearbyAirports: [
				"ILM",
				"EWN",
			],
		},
		{
			location: "Oakland",
			IATA: "OAK",
			state: "CA",
			enplanements: 5.293,
			latitude: 37.721,
			longitude: -122.221,
			nearbyAirports: [
				"SFO",
				"SJC",
				"CCR",
				"STS",
			],
		},
		{
			location: "Ogden",
			IATA: "OGD",
			state: "UT",
			enplanements: 0.021,
			latitude: 41.195,
			longitude: -112.012,
			nearbyAirports: [
				"SLC",
				"LGU",
			],
		},
		{
			location: "Kahului, Maui",
			IATA: "OGG",
			state: "HI",
			enplanements: 3.416,
			latitude: 20.899,
			longitude: -156.43,
		},
		{
			location: "Ogdensburg",
			IATA: "OGS",
			state: "NY",
			enplanements: 0.006,
			latitude: 44.682,
			longitude: -75.463,
			nearbyAirports: [
				"MSS",
				"SLK",
			],
		},
		{
			location: "Oklahoma City",
			IATA: "OKC",
			state: "OK",
			enplanements: 2.244,
			latitude: 35.393,
			longitude: -97.601,
		},
		{
			location: "Wolf Point",
			IATA: "OLF",
			state: "MT",
			enplanements: 0.003,
			latitude: 48.095,
			longitude: -105.575,
			nearbyAirports: [
				"GGW",
			],
		},
		{
			location: "Omaha",
			IATA: "OMA",
			state: "NE",
			enplanements: 2.583,
			latitude: 41.303,
			longitude: -95.894,
			nearbyAirports: [
				"LNK",
			],
		},
		{
			location: "Nome",
			IATA: "OME",
			state: "AK",
			enplanements: 0.07,
			latitude: 64.513,
			longitude: -165.444,
		},
		{
			location: "Ontario",
			IATA: "ONT",
			state: "CA",
			enplanements: 3.495,
			latitude: 34.056,
			longitude: -117.601,
			nearbyAirports: [
				"BUR",
				"HHR",
				"LAX",
				"LGB",
				"SNA",
				"SBD",
				"RIV",
				"VNY",
			],
		},
		{
			location: "Chicago",
			IATA: "ORD",
			state: "IL",
			enplanements: 25.076,
			latitude: 41.977,
			longitude: -87.908,
			nearbyAirports: [
				"MDW",
				"MKE",
				"GYY",
			],
		},
		{
			location: "Norfolk",
			IATA: "ORF",
			state: "VA",
			enplanements: 2.195,
			latitude: 36.895,
			longitude: -76.201,
			nearbyAirports: [
				"PHF",
			],
		},
		{
			location: "Worcester",
			IATA: "ORH",
			state: "MA",
			enplanements: 0.113,
			latitude: 42.267,
			longitude: -71.876,
		},
		{
			location: "North Bend",
			IATA: "OTH",
			state: "OR",
			enplanements: 0.02,
			latitude: 43.417,
			longitude: -124.247,
		},
		{
			location: "Kotzebue",
			IATA: "OTZ",
			state: "AK",
			enplanements: 0.061,
			latitude: 66.885,
			longitude: -162.598,
		},
		{
			location: "Owensboro",
			IATA: "OWB",
			state: "KY",
			enplanements: 0.009,
			latitude: 37.739,
			longitude: -87.167,
			nearbyAirports: [
				"EVV",
			],
		},
		{
			location: "Norwood",
			IATA: "OWD",
			state: "MA",
			enplanements: 0.017,
			latitude: 42.1783,
			longitude: -71.1759,
			nearbyAirports: [
				"BOS",
			],
		},
		{
			location: "Everett",
			IATA: "PAE",
			state: "WA",
			enplanements: 0.276,
			latitude: 47.907,
			longitude: -122.282,
			nearbyAirports: [
				"SEA",
				"BFI",
			],
		},
		{
			location: "Paducah",
			IATA: "PAH",
			state: "KY",
			enplanements: 0.013,
			latitude: 37.06,
			longitude: -88.773,
			nearbyAirports: [
				"MWA",
				"CGI",
			],
		},
		{
			location: "Plattsburgh",
			IATA: "PBG",
			state: "NY",
			enplanements: 0.093,
			latitude: 44.651,
			longitude: -73.468,
			nearbyAirports: [
				"BTV",
			],
		},
		{
			location: "West Palm Beach",
			IATA: "PBI",
			state: "FL",
			enplanements: 3.627,
			latitude: 26.683,
			longitude: -80.096,
			nearbyAirports: [
				"MIA",
				"FLL",
				"PBI",
			],
		},
		{
			location: "Pendleton",
			IATA: "PDT",
			state: "OR",
			enplanements: 0.007,
			latitude: 45.695,
			longitude: -118.843,
			nearbyAirports: [
				"PSC",
				"ALW",
			],
			"qrImpact": -0.5,
		},
		{
			location: "Portland",
			IATA: "PDX",
			state: "OR",
			enplanements: 8.639,
			latitude: 45.589,
			longitude: -122.597,
			nearbyAirports: [
				"SLE",
			],
		},
		{
			location: "Page",
			IATA: "PGA",
			state: "AZ",
			enplanements: 0.022,
			latitude: 36.926,
			longitude: -111.448,
		},
		{
			location: "Punta Gorda",
			IATA: "PGD",
			state: "FL",
			enplanements: 0.957,
			latitude: 26.919,
			longitude: -81.991,
			nearbyAirports: [
				"RSW",
			],
		},
		{
			location: "Greenville",
			IATA: "PGV",
			state: "NC",
			enplanements: 0.042,
			latitude: 35.636,
			longitude: -77.384,
		},
		{
			location: "Newport News",
			IATA: "PHF",
			state: "VA",
			enplanements: 0.099,
			latitude: 37.132,
			longitude: -76.493,
			nearbyAirports: [
				"ORF",
			],
		},
		{
			location: "Philadelphia",
			IATA: "PHL",
			state: "PA",
			enplanements: 15.102,
			latitude: 39.872,
			longitude: -75.241,
			nearbyAirports: [
				"ILG",
			],
		},
		{
			location: "Phoenix",
			IATA: "PHX",
			state: "AZ",
			enplanements: 19.596,
			latitude: 33.434,
			longitude: -112.012,
			nearbyAirports: [
				"AZA",
				"SCF",
			],
		},
		{
			location: "Peoria",
			IATA: "PIA",
			state: "IL",
			enplanements: 0.343,
			latitude: 40.664,
			longitude: -89.693,
			nearbyAirports: [
				"BMI",
			],
		},
		{
			location: "Hattiesburg",
			IATA: "PIB",
			state: "MS",
			enplanements: 0.016,
			latitude: 31.467,
			longitude: -89.337,
		},
		{
			location: "Tampa / St. Petersburg",
			IATA: "PIE",
			state: "FL",
			enplanements: 1.228,
			latitude: 27.909,
			longitude: -82.687,
			nearbyAirports: [
				"TPA",
				"SRQ",
				"LAL",
			],
		},
		{
			location: "Pocatello",
			IATA: "PIH",
			state: "ID",
			enplanements: 0.025,
			latitude: 42.91,
			longitude: -112.596,
			nearbyAirports: [
				"IDA",
			],
		},
		{
			location: "Pierre",
			IATA: "PIR",
			state: "SD",
			enplanements: 0.035,
			latitude: 44.383,
			longitude: -100.286,
		},
		{
			location: "Pittsburgh",
			IATA: "PIT",
			state: "PA",
			enplanements: 4.862,
			latitude: 40.491,
			longitude: -80.233,
			nearbyAirports: [
				"LBE",
			],
		},
		{
			location: "Parkersburg",
			IATA: "PKB",
			state: "WV",
			enplanements: 0.004,
			latitude: 39.345,
			longitude: -81.439,
		},
		{
			location: "Pellston",
			IATA: "PLN",
			state: "MI",
			enplanements: 0.031,
			latitude: 45.571,
			longitude: -84.797,
		},
		{
			location: "Pensacola",
			IATA: "PNS",
			state: "FL",
			enplanements: 1.528,
			latitude: 30.473,
			longitude: -87.187,
			nearbyAirports: [
				"ECP",
				"VPS",
				"GUF",
			],
		},
		{
			location: "Pago Pago",
			IATA: "PPG",
			state: "AS",
			enplanements: 0.055,
			latitude: -14.332,
			longitude: -170.712,
		},
		{
			location: "Presque Isle",
			IATA: "PQI",
			state: "ME",
			enplanements: 0.022,
			latitude: 46.689,
			longitude: -68.045,
		},
		{
			location: "Prescott",
			IATA: "PRC",
			state: "AZ",
			enplanements: 0.025,
			latitude: 34.655,
			longitude: -112.419,
			nearbyAirports: [
				"SDX",
			],
		},
		{
			location: "Pasco",
			IATA: "PSC",
			state: "WA",
			enplanements: 0.477,
			latitude: 46.265,
			longitude: -119.119,
			nearbyAirports: [
				"ALW",
				"PDT",
			],
		},
		{
			location: "Ponce",
			IATA: "PSE",
			state: "PR",
			enplanements: 0.138,
			latitude: 18.009,
			longitude: -66.565,
		},
		{
			location: "Petersburg",
			IATA: "PSG",
			state: "AK",
			enplanements: 0.025,
			latitude: 56.801,
			longitude: -132.946,
		},
		{
			location: "Portsmouth",
			IATA: "PSM",
			state: "NH",
			enplanements: 0.1,
			latitude: 43.078,
			longitude: -70.823,
		},
		{
			location: "Palm Springs",
			IATA: "PSP",
			state: "CA",
			enplanements: 1.618,
			latitude: 33.83,
			longitude: -116.507,
			nearbyAirports: [
				"TRM",
				"SBD"
			],
		},
		{
			location: "Pueblo",
			IATA: "PUB",
			state: "CO",
			enplanements: 0.008,
			latitude: 38.2875,
			longitude: -104.495278,
		},
		{
			location: "Pullman",
			IATA: "PUW",
			state: "WA",
			enplanements: 0.065,
			latitude: 46.742,
			longitude: -117.112,
			nearbyAirports: [
				"LWS",
			],
		},
		{
			location: "Provincetown",
			IATA: "PVC",
			state: "MA",
			enplanements: 0.007,
			latitude: 42.072,
			longitude: -70.221,
		},
		{
			location: "Providence",
			IATA: "PVD",
			state: "RI",
			enplanements: 1.985,
			latitude: 41.722,
			longitude: -71.428,
		},
		{
			location: "Provo",
			IATA: "PVU",
			state: "UT",
			enplanements: 0.455,
			latitude: 40.219,
			longitude: -111.723,
			nearbyAirports: [
				"SLC",
				"OGD",
			],
		},
		{
			location: "Portland",
			IATA: "PWM",
			state: "ME",
			enplanements: 1.222,
			latitude: 43.646,
			longitude: -70.309,
			nearbyAirports: [
				"AUG",
			],
		},
		{
			location: "Rapid City",
			IATA: "RAP",
			state: "SD",
			enplanements: 0.418,
			latitude: 44.045,
			longitude: -103.057,
		},
		{
			location: "Redding",
			IATA: "RDD",
			state: "CA",
			enplanements: 0.089,
			latitude: 40.509,
			longitude: -122.293,
		},
		{
			location: "Bend / Redmond",
			IATA: "RDM",
			state: "OR",
			enplanements: 0.601,
			latitude: 44.254,
			longitude: -121.15,
		},
		{
			location: "Raleigh",
			IATA: "RDU",
			state: "NC",
			enplanements: 7.584,
			latitude: 35.878,
			longitude: -78.787,
		},
		{
			location: "Rockford",
			IATA: "RFD",
			state: "IL",
			enplanements: 0.132,
			latitude: 42.195,
			longitude: -89.097,
		},
		{
			location: "Rhinelander",
			IATA: "RHI",
			state: "WI",
			enplanements: 0.025,
			latitude: 45.631,
			longitude: -89.467,
		},
		{
			location: "Richmond",
			IATA: "RIC",
			state: "VA",
			enplanements: 2.456,
			latitude: 37.505,
			longitude: -77.32,
		},
		{
			location: "Riverton",
			IATA: "RIW",
			state: "WY",
			enplanements: 0.022,
			latitude: 43.064,
			longitude: -108.46,
		},
		{
			location: "Rockland",
			IATA: "RKD",
			state: "ME",
			enplanements: 0.013,
			latitude: 44.06,
			longitude: -69.1,
		},
		{
			location: "Rock Springs",
			IATA: "RKS",
			state: "WY",
			enplanements: 0.022,
			latitude: 41.594,
			longitude: -109.065,
		},
		{
			location: "Reno",
			IATA: "RNO",
			state: "NV",
			enplanements: 2.228,
			latitude: 39.499,
			longitude: -119.768,
			nearbyAirports: [
				"TKF",
			],
		},
		{
			location: "Roanoke",
			IATA: "ROA",
			state: "VA",
			enplanements: 0.382,
			latitude: 37.325,
			longitude: -79.975,
			nearbyAirports: [
				"LYH",
			],
		},
		{
			location: "Rochester",
			IATA: "ROC",
			state: "NY",
			enplanements: 1.332,
			latitude: 43.119,
			longitude: -77.672,
		},
		{
			location: "Rota",
			IATA: "ROP",
			state: "MP",
			enplanements: 0.011,
			latitude: 14.18,
			longitude: -214.75,
		},
		{
			location: "Koror",
			IATA: "ROR",
			state: "PW",
			enplanements: 1.249,
			latitude: 7.367222,
			longitude: -225.455833,
		},
		{
			location: "Roswell",
			IATA: "ROW",
			state: "NM",
			enplanements: 0.049,
			latitude: 33.3,
			longitude: -104.529,
		},
		{
			location: "Rochester",
			IATA: "RST",
			state: "MN",
			enplanements: 0.099,
			latitude: 43.908,
			longitude: -92.5,
		},
		{
			location: "Fort Myers",
			IATA: "RSW",
			state: "FL",
			enplanements: 5.425,
			latitude: 26.536,
			longitude: -81.755,
			nearbyAirports: [
				"PGD",
				"APF",
			],
		},
		{
			location: "Rutland",
			IATA: "RUT",
			state: "VT",
			enplanements: 0.005,
			latitude: 43.53,
			longitude: -72.95,
			"qrImpact": -0.5,
		},
		{
			location: "Safford",
			IATA: "SAD",
			latitude: 32.85,
			longitude: -109.63,
			state: "AZ",
			enplanements: 0.002,
			"qrImpact": -1,
		},
		{
			location: "Santa Fe",
			IATA: "SAF",
			state: "NM",
			enplanements: 0.18,
			latitude: 35.617,
			longitude: -106.089,
			nearbyAirports: [
				"ABQ",
			],
		},
		{
			location: "San Diego",
			IATA: "SAN",
			state: "CA",
			enplanements: 12.78,
			latitude: 32.734,
			longitude: -117.19,
			nearbyAirports: [
				"CLD",
			],
		},
		{
			location: "San Antonio",
			IATA: "SAT",
			state: "TX",
			enplanements: 5.467,
			latitude: 29.534,
			longitude: -98.469,
		},
		{
			location: "Savannah",
			IATA: "SAV",
			state: "GA",
			enplanements: 2.021,
			latitude: 32.128,
			longitude: -81.202,
			nearbyAirports: [
				"HHH",
			],
		},
		{
			location: "Santa Barbara",
			IATA: "SBA",
			state: "CA",
			enplanements: 0.696,
			latitude: 34.426,
			longitude: -119.842,
			nearbyAirports: [
				"SMX",
				"SBP",
			],
		},
		{
			location: "San Bernadino",
			IATA: "SBD",
			state: "CA",
			enplanements: 0.02,
			latitude: 34.095,
			longitude: -117.235,
			nearbyAirports: [
				"BUR",
				"HHR",
				"LAX",
				"LGB",
				"SNA",
				"ONT",
				"RIV",
				"VNY",
				"PSP",
			],
		},
		{
			location: "South Bend",
			IATA: "SBN",
			state: "IN",
			enplanements: 0.455,
			latitude: 41.708,
			longitude: -86.317,
		},
		{
			location: "San Luis Obispo",
			IATA: "SBP",
			state: "CA",
			enplanements: 0.366,
			latitude: 35.237,
			longitude: -120.643,
		},
		{
			location: "Salisbury",
			IATA: "SBY",
			state: "MD",
			enplanements: 0.06,
			latitude: 38.34,
			longitude: -75.509,
		},
		{
			location: "Deadhorse",
			IATA: "SCC",
			state: "AK",
			enplanements: 0.097,
			latitude: 70.195,
			longitude: -148.465,
		},
		{
			location: "State College",
			IATA: "SCE",
			state: "PA",
			enplanements: 0.134,
			latitude: 40.84917,
			longitude: -77.84861,
		},
		{
			location: "Scottsdale",
			IATA: "SCF",
			enplanements: 0.012,
			state: "AZ",
			longitude: -111.91,
			latitude: 33.63,
			nearbyAirports: [
				"PHX",
				"AZA",
			],
			"qrImpact": -1,
		},
		{
			location: "Stockton",
			IATA: "SCK",
			state: "CA",
			enplanements: 0.064,
			latitude: 37.894,
			longitude: -121.239,
			nearbyAirports: [
				"SMF",
				"MCE",
				"MOD",
			],
		},
		{
			location: "Louisville",
			IATA: "SDF",
			state: "KY",
			enplanements: 2.343,
			latitude: 38.174,
			longitude: -85.736,
		},
		{
			location: "Sidney",
			IATA: "SDY",
			state: "MT",
			enplanements: 0.007,
			latitude: 47.707,
			longitude: -104.193,
			nearbyAirports: [
				"XWA",
			],
			"qrImpact": -0.5,
		},
		{
			location: "Seattle / Tacoma",
			IATA: "SEA",
			state: "WA",
			enplanements: 24.415,
			latitude: 47.45,
			longitude: -122.312,
			nearbyAirports: [
				"BFI",
				"PAE",
				"OLM",
			],
		},
		{
			location: "Sanford",
			IATA: "SFB",
			state: "FL",
			enplanements: 1.413,
			latitude: 28.777,
			longitude: -81.235,
			nearbyAirports: [
				"MCO",
				"DAB"
			],
		},
		{
			location: "San Francisco",
			IATA: "SFO",
			state: "CA",
			enplanements: 23.079,
			latitude: 37.619,
			longitude: -122.375,
			nearbyAirports: [
				"OAK",
				"SQL",
				"SJC",
				"CCR",
				"STS",
			],
		},
		{
			location: "Springfield",
			IATA: "SGF",
			state: "MO",
			enplanements: 0.702,
			latitude: 37.246,
			longitude: -93.389,
			nearbyAirports: [
				"BKG",
				"HRO",
			],
		},
		{
			location: "St. George",
			IATA: "SGU",
			state: "UT",
			enplanements: 0.261,
			latitude: 37.036,
			longitude: -113.51,
			nearbyAirports: [
				"CDC",
			],
		},
		{
			location: "Skagaway",
			IATA: "SGY",
			state: "AK",
			enplanements: 0.005,
			latitude: 59.46,
			longitude: -135.317,
			nearbyAirports: [
				"HNS",
			],
		},
		{
			location: "Staunton / Harrisonburg",
			IATA: "SHD",
			state: "VA",
			enplanements: 0.009,
			latitude: 38.264,
			longitude: -78.896,
			nearbyAirports: [
				"CHO",
			],
		},
		{
			location: "Sheridan",
			IATA: "SHR",
			state: "WY",
			enplanements: 0.029,
			latitude: 44.769,
			longitude: -106.98,
		},
		{
			location: "Shreveport",
			IATA: "SHV",
			state: "LA",
			enplanements: 0.352,
			latitude: 32.447,
			longitude: -93.826,
		},
		{
			location: "San Juan (Isla Grande)",
			IATA: "SIG",
			enplanements: 0.027,
			state: "PR",
			longitude: -66.1,
			latitude: 18.46,
			nearbyAirports: [
				"SJU",
			],
			"qrImpact": -1,
		},
		{
			location: "Sitka",
			IATA: "SIT",
			state: "AK",
			enplanements: 0.098,
			latitude: 57.047,
			longitude: -135.361,
		},
		{
			location: "San Jose",
			IATA: "SJC",
			state: "CA",
			enplanements: 5.822,
			latitude: 37.363,
			longitude: -121.929,
			nearbyAirports: [
				"SFO",
				"SQL",
				"OAK",
				"CCR",
			],
		},
		{
			location: "San Angelo",
			IATA: "SJT",
			state: "TX",
			enplanements: 0.049,
			latitude: 31.358,
			longitude: -100.496,
		},
		{
			location: "San Juan",
			IATA: "SJU",
			state: "PR",
			enplanements: 6.491,
			latitude: 18.439,
			longitude: -66.002,
			nearbyAirports: [
				"SIG",
			],
		},
		{
			location: "Salt Lake City",
			IATA: "SLC",
			state: "UT",
			enplanements: 13.544,
			latitude: 40.788,
			longitude: -111.978,
			nearbyAirports: [
				"OGD",
				"PVU",
				"LGU",
			],
		},
		{
			location: "Salem",
			IATA: "SLE",
			state: "OR",
			enplanements: 0.128,
			latitude: 44.91,
			longitude: -123.003,
			nearbyAirports: [
				"PDX",
			],
		},
		{
			location: "Saranac Lake",
			IATA: "SLK",
			state: "NY",
			enplanements: 0.005,
			latitude: 44.385,
			longitude: -74.206,
			nearbyAirports: [
				"OGS",
				"MSS",
			],
		},
		{
			location: "Salina",
			IATA: "SLN",
			state: "KS",
			enplanements: 0.023,
			latitude: 38.791,
			longitude: -97.652,
			"qrImpact": -0.5,
		},
		{
			location: "Sacramento",
			IATA: "SMF",
			state: "CA",
			enplanements: 6.679,
			latitude: 38.695,
			longitude: -121.591,
			nearbyAirports: [
				"SCK",
			],
		},
		{
			location: "Santa Maria",
			IATA: "SMX",
			state: "CA",
			enplanements: 0.014,
			latitude: 34.9,
			longitude: -120.458,
			nearbyAirports: [
				"SBP",
			],
		},
		{
			location: "Santa Ana",
			IATA: "SNA",
			state: "CA",
			enplanements: 5.37,
			latitude: 33.676,
			longitude: -117.868,
			nearbyAirports: [
				"BUR",
				"HHR",
				"LAX",
				"LGB",
				"ONT",
				"VNY",
			],
		},
		{
			location: "Show Low",
			IATA: "SOW",
			state: "AZ",
			enplanements: 0.004,
			latitude: 34.265,
			longitude: -110.006,
			"qrImpact": -0.5,
		},
		{
			location: "Springfield",
			IATA: "SPI",
			state: "IL",
			enplanements: 0.252,
			latitude: 39.845,
			longitude: -89.678,
			nearbyAirports: [
				"DEC",
			],
		},
		{
			location: "Saipan",
			IATA: "SPN",
			state: "MP",
			enplanements: 0.234,
			latitude: 15.12,
			longitude: -214.28,
		},
		{
			location: "Wichita Falls",
			IATA: "SPS",
			state: "TX",
			enplanements: 0.03,
			latitude: 33.989,
			longitude: -98.492,
			nearbyAirports: [
				"LAW",
			],
		},
		{
			location: "San Carlos",
			IATA: "SQL",
			state: "CA",
			enplanements: 0.014,
			latitude: 37.511944,
			longitude: -122.249444,
			nearbyAirports: [
				"OAK",
				"SFO",
				"SJC",
			],
		},
		{
			location: "Sarasota",
			IATA: "SRQ",
			state: "FL",
			enplanements: 1.612,
			latitude: 27.395,
			longitude: -82.554,
			nearbyAirports: [
				"TPA",
				"PIE",
			],
		},
		{
			location: "St. Cloud",
			IATA: "STC",
			state: "MN",
			enplanements: 0.024,
			latitude: 45.546,
			longitude: -94.059,
		},
		{
			location: "St. Louis",
			IATA: "STL",
			state: "MO",
			enplanements: 7.807,
			latitude: 38.749,
			longitude: -90.37,
			nearbyAirports: [
				"BLV",
				"CPS",
			],
		},
		{
			location: "Santa Rosa",
			IATA: "STS",
			state: "CA",
			enplanements: 0.383,
			latitude: 38.51,
			longitude: -122.813,
			nearbyAirports: [
				"SFO",
				"OAK",
			],
		},
		{
			location: "St. Thomas",
			IATA: "STT",
			state: "VI",
			enplanements: 0.822,
			latitude: 18.337,
			longitude: -64.973,
		},
		{
			location: "St. Croix",
			IATA: "STX",
			state: "VI",
			enplanements: 0.265,
			latitude: 17.702,
			longitude: -64.802,
		},
		{
			location: "Sun Valley",
			IATA: "SUN",
			state: "ID",
			enplanements: 0.121,
			latitude: 43.504,
			longitude: -114.296,
		},
		{
			location: "Sioux City",
			IATA: "SUX",
			state: "IA",
			enplanements: 0.028,
			latitude: 42.401,
			longitude: -96.384,
		},
		{
			location: "Silver City",
			IATA: "SVC",
			state: "NM",
			enplanements: 0.007,
			latitude: 32.637,
			longitude: -108.156,
		},
		{
			location: "Newburgh (Stewart)",
			IATA: "SWF",
			state: "NY",
			enplanements: 0.343,
			latitude: 41.504,
			longitude: -74.105,
		},
		{
			location: "Stillwater",
			IATA: "SWO",
			state: "OK",
			enplanements: 0.035,
			latitude: 36.161,
			longitude: -97.086,
		},
		{
			location: "Syracuse",
			IATA: "SYR",
			state: "NY",
			enplanements: 1.487,
			latitude: 43.111,
			longitude: -76.106,
		},
		{
			location: "Fort Leonard Wood",
			IATA: "TBN",
			state: "MO",
			enplanements: 0.011,
			latitude: 37.742,
			longitude: -92.141,
		},
		{
			location: "Teterboro",
			IATA: "TEB",
			state: "NJ",
			enplanements: 0.013,
			latitude: 40.85,
			longitude: -74.060833,
			nearbyAirports: [
				"JFK",
				"EWR",
				"LGA",
				"ISP",
				"HPN",
			],
		},
		{
			location: "Telluride",
			IATA: "TEX",
			state: "CO",
			enplanements: 0.011,
			latitude: 37.954,
			longitude: -107.909,
		},
		{
			location: "Tinian",
			IATA: "TIQ",
			state: "MP",
			enplanements: 0.031,
			latitude: 15,
			longitude: -214.38,
		},
		{
			location: "Tallahassee",
			IATA: "TLH",
			state: "FL",
			enplanements: 0.469,
			latitude: 30.397,
			longitude: -84.351,
		},
		{
			location: "Toledo",
			IATA: "TOL",
			state: "OH",
			enplanements: 0.067,
			latitude: 41.587,
			longitude: -83.808,
		},
		{
			location: "Tampa",
			IATA: "TPA",
			state: "FL",
			enplanements: 12.076,
			latitude: 27.975,
			longitude: -82.533,
			nearbyAirports: [
				"PIE",
				"SRQ",
				"LAL",
			],
		},
		{
			location: "Tri-Cities",
			IATA: "TRI",
			state: "TN",
			enplanements: 0.23,
			latitude: 36.475,
			longitude: -82.407,
		},
		{
			location: "Taos",
			IATA: "TSM",
			state: "NM",
			enplanements: 0.012,
			latitude: 36.458056,
			longitude: -105.6725,
			nearbyAirports: [
				"AXX",
			],
		},
		{
			location: "Trenton",
			IATA: "TTN",
			state: "NJ",
			enplanements: 0.342,
			latitude: 40.277,
			longitude: -74.813,
		},
		{
			location: "Tulsa",
			IATA: "TUL",
			state: "OK",
			enplanements: 1.627,
			latitude: 36.198,
			longitude: -95.888,
		},
		{
			location: "Tupelo",
			IATA: "TUP",
			state: "MS",
			enplanements: 0.016,
			latitude: 34.269,
			longitude: -88.77,
		},
		{
			location: "Tucson",
			IATA: "TUS",
			state: "AZ",
			enplanements: 1.96,
			latitude: 32.117,
			longitude: -110.941,
		},
		{
			location: "Traverse City",
			IATA: "TVC",
			state: "MI",
			enplanements: 0.393,
			latitude: 44.742,
			longitude: -85.582,
			nearbyAirports: [
				"MBL",
			],
		},
		{
			location: "Thief River Falls",
			IATA: "TVF",
			state: "MN",
			enplanements: 0.009,
			latitude: 48.066,
			longitude: -96.185,
			nearbyAirports: [
				"GFK",
			],
			"qrImpact": -0.5,
		},
		{
			location: "Twin Falls",
			IATA: "TWF",
			state: "ID",
			enplanements: 0.032,
			latitude: 42.482,
			longitude: -114.488,
		},
		{
			location: "Texarkana",
			IATA: "TXK",
			state: "AR",
			enplanements: 0.036,
			latitude: 33.454,
			longitude: -93.991,
			nearbyAirports: [
				"ELD",
			],
		},
		{
			location: "Tyler",
			IATA: "TYR",
			state: "TX",
			enplanements: 0.051,
			latitude: 32.354,
			longitude: -95.403,
			nearbyAirports: [
				"GGG",
			],
		},
		{
			location: "Knoxville",
			IATA: "TYS",
			state: "TN",
			enplanements: 1.639,
			latitude: 35.811,
			longitude: -83.994,
		},
		{
			location: "Quincy",
			IATA: "UIN",
			state: "IL",
			enplanements: 0.004,
			latitude: 39.942,
			longitude: -91.192,
			nearbyAirports: [
				"IRK",
			],
		},
		{
			location: "Unalakleet",
			IATA: "UNK",
			state: "AK",
			enplanements: 0.007,
			latitude: 63.888,
			longitude: -160.799,
		},
		{
			location: "Concord",
			IATA: "USA",
			state: "NC",
			enplanements: 0.132,
			latitude: 35.38778,
			longitude: -80.70917,
			nearbyAirports: [
				"CLT",
			],
		},
		{
			location: "Victoria",
			IATA: "VCT",
			state: "TX",
			enplanements: 0.014,
			latitude: 28.854,
			longitude: -96.919,
		},
		{
			location: "Valdez",
			IATA: "VDZ",
			state: "AK",
			enplanements: 0.003,
			latitude: 61.134,
			longitude: -146.245,
		},
		{
			location: "Vernal",
			IATA: "VEL",
			state: "UT",
			enplanements: 0.011,
			latitude: 40.436,
			longitude: -109.511,
		},
		{
			location: "Valdosta",
			IATA: "VLD",
			state: "GA",
			enplanements: 0.047,
			latitude: 30.781,
			longitude: -83.276,
		},
		{
			location: "Fort Walton Beach",
			IATA: "VPS",
			state: "FL",
			enplanements: 1.065,
			latitude: 30.483,
			longitude: -86.526,
			nearbyAirports: [
				"PNS",
				"ECP",
			],
		},
		{
			location: "Vieques",
			IATA: "VQS",
			state: "PR",
			enplanements: 0.038,
			latitude: 18.135,
			longitude: -65.494,
		},
		{
			location: "Vero Beach",
			IATA: "VRB",
			state: "FL",
			enplanements: 0.089,
			latitude: 27.656,
			longitude: -80.418,
			nearbyAirports: [
				"MLB",
			],
		},
		{
			location: "Wrangell",
			IATA: "WRG",
			state: "AK",
			enplanements: 0.015,
			latitude: 56.484,
			longitude: -132.37,
		},
		{
			location: "Westerly",
			IATA: "WST",
			state: "RI",
			enplanements: 0.012,
			latitude: 41.35,
			longitude: -71.803,
		},
		{
			location: "West Yellowstone",
			IATA: "WYS",
			state: "MT",
			enplanements: 0.03,
			latitude: 44.688,
			longitude: -111.118,
			nearbyAirports: [
				"BTM",
				"BZN",
			],
		},
		{
			location: "Fayetteville",
			IATA: "XNA",
			state: "AR",
			enplanements: 1.123,
			latitude: 36.282,
			longitude: -94.308,
			nearbyAirports: [
				"FSM",
			],
		},
		{
			location: "Williston",
			IATA: "XWA",
			state: "ND",
			enplanements: 0.1,
			latitude: 48.26,
			longitude: -103.751,
			nearbyAirports: [
				"SDY",
			],
		},
		{
			location: "Yakutat",
			IATA: "YAK",
			state: "AK",
			enplanements: 0.012,
			latitude: 59.503,
			longitude: -139.66,
		},
		{
			location: "Yakima",
			IATA: "YKM",
			state: "WA",
			enplanements: 0.071,
			latitude: 46.568,
			longitude: -120.544,
		},
		{
			location: "Youngstown / Warren",
			IATA: "YNG",
			enplanements: 0.009,
			state: "OH",
			longitude: -80.68,
			latitude: 41.27,
			nearbyAirports: [
				"CAK",
			],
			"qrImpact": -1,
		},
		{
			location: "Yuma",
			IATA: "YUM",
			state: "AZ",
			enplanements: 0.11,
			latitude: 32.65667,
			longitude: -114.60611,
			nearbyAirports: [
				"IPL",
			],
		},
	{
		location: 'Bowling Green',
		IATA: 'BWG',
		enplanements: 0.004,
		state: 'KY',
		longitude: -86.42,
		latitude: 36.96,
		qrImpact: -1
	},
	{
		location: 'McCook',
		IATA: 'MCK',
		enplanements: 0.003,
		state: 'NE',
		longitude: -100.59,
		latitude: 40.21,
		nearbyAirports: ['LBF'],
		qrImpact: -1
	},
	{
		location: 'Wendover',
		IATA: 'ENV',
		longitude: -114.03,
		latitude: 40.72,
		state: 'UT',
		enplanements: 0.023,
		qrImpact: -1
	},
		{
			location: 'Glendive',
			IATA: 'GDV',
			enplanements: 0.002,
			state: 'MT',
			longitude: -104.81,
			latitude: 47.14,
			qrImpact: -1
		},
		{
			location: 'Chadron',
			IATA: 'CDR',
			enplanements: 0.003,
			state: 'NE',
			longitude: -103.1,
			latitude: 42.84,
			qrImpact: -1
		},
		{
			location: 'Ely',
			IATA: 'ELY',
			enplanements: 0.001,
			state: 'NV',
			longitude: -114.84,
			latitude: 39.3,
			qrImpact: -1
		},
		{
			location: 'Farmington',
			IATA: 'FMN',
			enplanements: 0.004,
			state: 'NM',
			longitude: -108.23,
			latitude: 36.74,
			qrImpact: -1
		},
		{
			location: 'Baker City',
			IATA: 'BKE',
			enplanements: 0.001,
			state: 'OR',
			longitude: -117.81,
			latitude: 44.84,
			qrImpact: -1
		},
		{
			location: 'Sierra Vista',
			IATA: 'FHU',
			enplanements: 0.002,
			state: 'AZ',
			longitude: -110.34,
			latitude: 31.59,
			qrImpact: -1
		},
		{
			location: 'Angel Fire',
			IATA: 'AXX',
			latitude: 36.42,
			longitude: -105.29,
			state: 'NM',
			enplanements: 0.002,
			qrImpact: -1,
			nearbyAirports: ['TSM']
		},
		{
			location: 'Logan',
			IATA: 'LGU',
			enplanements: 0.007,
			state: 'UT',
			longitude: -111.85,
			latitude: 41.79,
			nearbyAirports: ['OGD', 'SLC'],
			qrImpact: -1
		},
		{
			location: 'Inyokern',
			IATA: 'IYK',
			latitude: 35.66,
			longitude: -117.83,
			state: 'CA',
			enplanements: 0.002,
			qrImpact: -1
		},
		{
			location: 'Las Cruces',
			IATA: 'LRU',
			enplanements: 0.002,
			state: 'NM',
			longitude: -106.92,
			latitude: 32.29,
			nearbyAirports: ['ELP'],
			qrImpact: -1
		},
		{
			location: 'Cincinnati',
			IATA: 'LUK',
			enplanements: 0.022,
			state: 'OH',
			longitude: -84.42,
			latitude: 39.1,
			nearbyAirports: ['CVG'],
			qrImpact: -1
		},
		{
			location: 'Olympia',
			IATA: 'OLM',
			latitude: 46.97,
			longitude: -122.9,
			state: 'WA',
			enplanements: 0.012,
			qrImpact: -1,
			nearbyAirports: ['SEA', 'BFI']
		},
		{
			location: 'Visalia',
			IATA: 'VIS',
			latitude: 36.32,
			longitude: -119.39,
			state: 'CA',
			enplanements: 0.009,
			qrImpact: -1,
			nearbyAirports: ['FAT']
		},
		{
			location: 'Titusville / Cocoa',
			IATA: 'TIX',
			latitude: 28.51,
			longitude: -80.8,
			state: 'FL',
			enplanements: 0.003,
			qrImpact: -1
		},
		{
			location: 'Winston-Salem',
			IATA: 'INT',
			enplanements: 0.01,
			state: 'NC',
			longitude: -80.22,
			latitude: 36.13,
			nearbyAirports: ['GSO'],
			qrImpact: -1
		},
		{
			location: 'Klamath Falls',
			IATA: 'LMT',
			latitude: 42.16,
			longitude: -121.73,
			state: 'OR',
			enplanements: 0.006,
			qrImpact: -1
		},
		{
			location: 'Oshkosh',
			IATA: 'OSH',
			latitude: 43.98,
			longitude: -88.56,
			state: 'WI',
			enplanements: 0.009,
			qrImpact: -1,
			nearbyAirports: ['ATW']
		},
		{
			location: 'Chico',
			IATA: 'CIC',
			latitude: 39.8,
			longitude: -121.86,
			state: 'CA',
			enplanements: 0.005,
			qrImpact: -1
		},
		{
			location: 'Naples',
			IATA: 'APF',
			latitude: 26.15,
			longitude: -81.78,
			state: 'FL',
			enplanements: 0.003,
			qrImpact: -1,
			nearbyAirports: ['RSW']
		},
		{
			location: 'New Bedford',
			IATA: 'EWB',
			enplanements: 0.002,
			state: 'MA',
			longitude: -70.96,
			latitude: 41.68,
			qrImpact: -1
		},
		{
			location: 'Port Angeles',
			IATA: 'CLM',
			latitude: 48.12,
			longitude: -123.50,
			state: 'WA',
			enplanements: 0.002,
			qrImpact: -1
		}
	];
	return airports.map((value: Partial<airportType>): airportType => {
		value.type = "nonHub";
		value.interestMode = false;
		value.connections = {};
		value.unassignedTravelers = 0;
		if (!value.enplanements) {
			value.enplanements = 0;
		}
		value.popularityChange = 1;
		value.gates = 0;
		return value as airportType;
	}).filter(filter);
}
// To get back up, Search 'ABE'
